### ISSUE TITLE
NMatrix extension for Cholesky decomposition of sparse matrices

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#154]
The code for this needs to be wrapped _in a separate gem_, probably to be called `nmatrix-cholmod`. It should be based, if possible on the following code:

http://www.cise.ufl.edu/research/sparse/cholmod/

Unfortunately, that code reads a matrix off the hard drive. Some research needs to be done to determine whether the algorithm can work for NMatrix's existing sparse types.

**Comment by agisga** [comment]
@thisMagpie did you have any luck with that? Or any insights for me if I want to work on this issue?

This feature would be extremely beneficial for a mixed models gem (which is one of the GSoC 2015 ideas).

**Comment by AdiChat** [comment]
@mohawkjohn Could you elucidate on the objective of the extension? The link is broken.
I would like to contribute on coding this extension after planning out the steps.
