### ISSUE TITLE
Move all ATLAS, LAPACK code into a separate gem or gems

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#155]
The best way to make NMatrix work in multiple environments is to ensure that other linear algebra libraries can be substituted in. For example, someone might want to use eigen3 instead of ATLAS.

This task requires a bit of design. There are some functions in NMatrix which are taken from ATLAS, but reimplemented natively. Do these stay? Or do they go? (Probably they stay in NMatrix, but a good argument against it might exist.)

So the ATLAS and LAPACK and CLAPACK stuff goes into a separate gem, which might be `nmatrix-atlas`, or something similar. Maybe there's another one for `nmatrix-lapack`, which includes those native LAPACK functions which *aren't* CLAPACK.

**Comment by v0dro** [comment]
Done by @wlevine.
