### ISSUE TITLE
Exact determinant and inverse calculations for yale and list 2x2 and 3x3

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#189]
Right now exact determinant calculations are disabled for Yale and list matrices, but allowed for dense, of sizes 2x2 and 3x3. This doesn't make a ton of sense. They're all pretty trivial calculations.

Someone needs to implement an algorithm which calculates 2x2 and 3x3 exact determinants for Yale and list matrices. It goes in `nm_det_exact` in `ruby_nmatrix.c`.

Subsequently, `nm_inverse_exact` can be adjusted, too; however, this requires the exact determinant calculation.

**Comment by spacewander** [comment]
Is it acceptable to cast yale/list matrix into dense matrix in the C code?
It's possible to implement algorithms separately for yale/list matrix, but this will make things more complex. Since we will have 3 types of stype, each has N dtype.

Currently we just support 2×2 and 3×3 matrices, so the extra cost may not be high.

**Comment by mohawkjohn** [comment]
Hey, sorry, just got back from vacation. I think it's probably preferred that casting only happen for very small matrices, and then there has to be some consideration of the trade-offs. For example, is it cheaper to cast and then calculate the determinant as a dense, or is it cheaper to simply calculate the determinant of a 3x3 yale matrix in Ruby code?

I suppose perhaps this issue is kind of a badly defined one. What we really want is determinant and inverse calculation for full Yale matrices, and for those casting would not be good (and people can already do that on their own). For list matrices, it's probably always appropriate to cast to Yale or dense first, just because of the way the data structure is laid out.

**Comment by spacewander** [comment]
@mohawkjohn 
So after checking the stype of a NMatrix, we need to do three actions according to the stype:

1. Dense: use old implementation to handle it
2. Yale: develop a new way to handle it
3. List: cast it to dense one.

Am I correct?

**Comment by mohawkjohn** [comment]
List: cast it to Yale, probably, unless it's got more than a certain number of elements in it. You'll want to derive an expression for when it's more efficient to cast to Yale and when more efficient to cast to dense.
