### ISSUE TITLE
Exposure of remaining CBLAS and CLAPACK functions

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#2]
Right now, only xgemm, xgemv, xgetrf, laswp, idamax, and a few others are implemented.

It'd be great if we could expose all of the CBLAS and ATLAS-CLAPACK functions.

Usually this means writing a templated version of the function in math.h which works for rational types (and possibly integers too). You override the templates for float, double, Complex64, and Complex128 and have those call `clapack_xxxxx` or `cblas_xxxxx`.

I usually just derive my templated version from whatever is in ATLAS' source (using the most recent version).

If I can't do that, e.g. with xgemm, I look at LAPACK or I use `f2c` to convert the original `DGEMM.F` (for example) to a C file, then I go through and rewrite it in a C++ style and make it maintainable.

**Comment by v0dro** [comment]
@wlevine can you confirm if these have been implemented in your plugins? Should I close this?

**Comment by wlevine** [comment]
No, I didn't expose any functions that weren't there before. There are a huge number of LAPACK functions, I don't even know which ones we would want to prioritize adding first.
