### ISSUE TITLE
Eigenvalue decomposition function on NMatrix

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#219]
Extends #19.

`geev` is exposed as a LAPACK function, but is terribly difficult to use. It'd be lovely if we could do eigenvalue decomposition directly on an NMatrix.

**Comment by rohit12** [comment]
I would like to take up this issue. I would like clarification on the issue though. Do I just have to calculate the second eigen vector?

**Comment by mohawkjohn** [comment]
Why only the second?

**Comment by rohit12** [comment]
The issue is not clear to me. That is why I am getting confused. It says that the second eigen vector is missing. So I assume that I have to calculate the second eigen vector?

**Comment by rohit12** [comment]
@mohawkjohn Could I get a clarification please? I would really like to start working on this.

**Comment by mohawkjohn** [comment]
Oh. Sorry, I misread some things in here (and was not near a computer all weekend).

The second eigenvector is probably being computed but is being lost when the size of the resulting NMatrix object is set. So, no, you don't have to compute the second eigenvector, you just have to figure out the problem with the Ruby/C interface.

**Comment by wlevine** [comment]
I had completely forgotten, but I actually did a lot of this last summer. The output from `NMatrix::LAPACK.geev` is in a much friendlier format than the original geev. See the [documentation](https://github.com/SciRuby/nmatrix/blob/c97c43a58d78ff226d0aeb009b13562bb6158066/lib/nmatrix/lapack_core.rb#L119) and the [specs](https://github.com/SciRuby/nmatrix/blob/ea3a544fc72dd614bb964053b89be476e45e5428/spec/lapack_core_spec.rb#L314). So the eigenvalues are already in a nicer format. I think the next step is to make a method `NMatrix#eigenvectors` or `NMatrix#eigen_decomposition` that would call NMatrix::LAPACK.geev on itself.

**Comment by mohawkjohn** [comment]
@wlevine Is it different enough that we should close this issue and open a new one?
