### ISSUE TITLE
NMatrix#gesvd with non-square matrices

### ISSUE THREAD

**Issue by yoongkang** [SciRuby/nmatrix#265]
Hi, I'm doing this quite late at night and this might be just me not fully understanding the library, but I think I came across a bug with the SVD feature. I'm trying to do SVD on the matrix example from wikipedia: http://en.wikipedia.org/wiki/Singular_value_decomposition

This is the gist: https://gist.github.com/yoongkang/b6a40abcce76b771742d

The product of the three component matrices isn't the same as the original matrix. I assume this is a bug?

**Comment by wlevine** [comment]
I think I found the problem here. It looks like the lapack functions work with arrays ordered in the fortran-style rather than C-style. By transposing the matrix `a` right before the call to `dgesvd_()` and transposing the matrices `u` and `vt` right after, I get the correct results. Is there a better way to work around this?

**Comment by wlevine** [comment]
OK, no need to do any transposes. Since M = U S V^T, we have M^T = V S^T U^T, so it's OK if we give lapack the transposed matrix, as long as we tell it it it's n x m instead of m x n and flip the meanings of u and vt. I'll fix this and submit a patch.

**Comment by wlevine** [comment]
The method described above gives us a valid singular value decomposition, but not the exact same one we would get by calling `dgesvd_` directly on M rather than on M^T. I'm not sure if this is a problem, would people expect our function to exactly match the original lapack one?

**Comment by mohawkjohn** [comment]
Well, it can't, I think. The original LAPACK method is column-major, and our storage is row-major. But I may be misremembering.
