### ISSUE TITLE
Sporadic segfaulting from NMatrix

### ISSUE THREAD

**Issue by fis** [SciRuby/nmatrix#277]
First, apologies in advance for providing only a sketchy bug report (feel free to close this issue as unproductive), but on the off chance the logs are enough to point at some obvious problem...

I have a piece of NMatrix-using code that does a very simple operation:

```
break if (s - ps).abs.mean.to_f < 0.000001
```

...where `s` and `ps` are 47x1-sized dense column vectors. Rarely, this results in a segfault somewhere inside `mean`, with the following (quite long) error log: https://dl.dropboxusercontent.com/u/113389132/Misc/20140924-nmatrix.txt

Unfortunately, I don't have a reproducible test case; so far, the bug has occurred after the piece of code had been online a day or two, and performed the above line maybe two-to-five thousand times. Re-running the latest tasks (which should lead to s and ps that are otherwise identical to the crashing input, except possibly a permutation) has always gone through with no issues. The system (a VPS) exhibits no other mysterious behavior that would suggest hardware troubles.

Equally unfortunately, the above has only been tested on the 0.1.0.rc5 release. I haven't been able to get the latest github code installed: the system in question is a Debian wheezy/stable install, with Ruby version "1.9.3.194-8.1+deb7u2" and ATLAS "3.8.4-9+deb7u1" installed from the Debian repository. Following the development code install instruction runs into versioning issues ("rake-compiler requires RubyGems version >= 1.8.25", and the suggested 'gem update --system' is disabled on Debian). To add insult to injury, the 0.1.0.rc5 release code (which installed cleanly with 'gem install') I currently have was compiled with distcc (the system in question does not have enough memory to compile all NMatrix components locally), which might well be a contributing factor.

**Comment by mohawkjohn** [comment]
Unclear if still a problem.
