### ISSUE TITLE
#delete_at for vectors

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#302]
We can have a delete_at method for 1-D NMatrix objects, where the element's index will be supplied and a vector with that element removed (compact) will result.

For example:

``` ruby

n = NMatrix.seq([5]).delete_at(2)
puts n
# => [0,1,2,4]
```

**Comment by mohawkjohn** [comment]
Keep in mind that an NMatrix is not an Array. In Arrays, it's relatively inexpensive to remove an item like this. In an NMatrix, it requires that all the elements be copied into a new vector.

In general, the design philosophy thus far has been to discourage operations that are expensive and more easily done with other data structures — mainly accomplished by not implementing certain functionalities.
