### ISSUE TITLE
Creating a meshgrid from given arrays/vectors

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#304]
Create a meshgrid similar to scipy meshgrids.

http://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html

**Comment by mohawkjohn** [comment]
This would be an excellent feature.

**Comment by sachaysl** [comment]
So I believe I've implemented such a feature. I haven't yet implemented the Copy or Sparse options or taken a look at Rspec or Rdoc though. I've also assumed the only valid inputs are ruby arrays and nmatrices and I am returning the required grids as nmatrices. What is the best way to proceed? 

Perhaps this is now irrelevant as I see Ivan claims to have already implemented this feature.

Sacha

**Comment by agarie** [comment]
@sachaysl yep, it seems he did it. We still need to review his pull request, tho.
