### ISSUE TITLE
Native quick sort

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#310]
There is no `sort` function defined on NMatrix currently.

How about a natively implemented quick sort which will accept the axis alongwhich sorting is to be performed and perform a in place quick sort along that axis?

For example:

``` ruby

n = N.new [3,3], [2,3,5,2,5,3,2,4,5]
# 2 3 5
# 2 5 3
# 2 4 5

n.sort 1 # sort along the columns OR n.sort(0) to sort along rows.
```

The arg will default to 0 otherwise.

**Comment by v0dro** [comment]
@cjfuller  @mohawkjohn thoughts?

**Comment by cjfuller** [comment]
I guess I could use some clarification on what usecase you're looking at for this.  Normally the notion of sorting a matrix doesn't really make sense.  Is there some case where this would be helpful?

Personally I'd prefer that if there's not some high-performance usecase for it but you still want it for convenience, you implement sorting as just a pure ruby function that does a `.to_a` (or whatever) on each slice along the specified axis, uses ruby's built-in sort, and then constructs a new NMatrix from the result.  That's considerably less work both to implement and to maintain, and we can always convert it to native code with the same interface if it's needed at some point.

**Comment by v0dro** [comment]
I look at NMatrix as more of an efficient data store that is capable of faster, more robust calculations than the standard ruby library has to offer, at the same time offering more variety to users.

Its more like a replacement for the really heavy data structures that ruby supplies (like arrays), but specifically tailored for high performance computing.

I feel that it should be useful in any ruby program that needs more speed at lesser resources, something that numpy does very well for Python programs.

Therefore, I think sorting at the native level is an essential utility.

**Comment by agarie** [comment]
But @v0dro, I too can't see a good use case in which you would constantly sort a matrix. How about going with the simpler implementation proposed by Colin (only in Ruby) and, if the need arises, propose a native implementation again? If you are sorting it only once in your program's lifetime, it probably shouldn't be problematic.

By the way, good job in creating issues and pull requests!

**Comment by mohawkjohn** [comment]
`NMatrix` is not a replacement for `Array`. Arrays do some things (like being reordered) really efficiently; this is what they're optimized for. NMatrix is not optimized for being reordered. Optimizing it for that purpose would cause it to be less efficient on those operations where it needs to be efficient. If that were not the case, we would just submit a whole bunch of patches for `Array` to make it more like a matrix.

It's fine to implement a sort method on NMatrix which does this, but it should be a convenience function which makes use of conversion to Array. That way we can rely on Array's built-in sort, which has had far more energy and testing put into it than an NMatrix native sort could ever.

**Comment by cjfuller** [comment]
(Note also that ruby's built-in array sort is implemented natively, so it's not completely ridiculous to use it.)

**Comment by v0dro** [comment]
Hmmm point.

I'll think I'll just code up a `sort` using @cjfuller's approach and send it through in a while. Should make things very convenient.
