### ISSUE TITLE
Possible anomaly in rational

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#311]
Heres my code:

```
In [12]: a=N.new [2,1], [-23/12, 6/5], dtype: :rational32
Out[12]: #<NMatrix:0x9a04264 shape:[2,1] dtype:rational32 stype:dense>

In [13]: puts a
[(-2/1), (1/1)]

In [14]: a=N.new [2,1], [Rational(-23/12), Rational(6/5)], dtype: :rational32
Out[14]: #<NMatrix:0x99cbb30 shape:[2,1] dtype:rational32 stype:dense>

In [15]: puts a
[(-2/1), (1/1)]

```

Shouldnt the numbers be stored as they are specifed?

**Comment by cjfuller** [comment]
No, this is correct behavior, though confusing.  Ruby evaluates -23/12 via integer division to -2 before NMatrix ever sees it.

So your first line of code is equivalent to:

`a = N.new [2, 1], [-2, 1], dtype: :rational32`, which is exactly what you're seeing.

You need to use ruby's built-in rational class:

`a = N.new [2, 1], [Rational(-23, 12), Rational(6, 5)], dtype: :rational32`
