### ISSUE TITLE
Working Yosemite install instructions

### ISSUE THREAD

**Issue by gbuesing** [SciRuby/nmatrix#319]
In case this is of help to anyone else -- this is an account of how I got NMatrix to install on Yosemite. Adapted from installation instructions on the [wiki](https://github.com/SciRuby/nmatrix/wiki/Installation#mac-os-x).
Note that step 3 requires an Apple Developer Program membership.

1. install latest version of gcc (4.9) via Homebrew

        brew install gcc

2. link /usr/bin/gcc to homebrew gcc

        sudo ln -nfs /usr/local/bin/gcc-4.9 /usr/bin/gcc
        sudo ln -nfs /usr/local/bin/g++-4.9 /usr/bin/g++

3. get libatlas.dylib via older XCode version (5.1.1)
libatlas.dylib isn't in Mac OS X SDKs beyond 10.8, so you need to get the old SDK via an older XCode.
download XCode 5.1.1 from:
http://adcdownload.apple.com/Developer_Tools/xcode_5.1.1/xcode_5.1.1.dmg (requires Apple Developer Program membership)
and install somewhere (I put in Applications, renaming it to XCode_511)

4. link libatlas.dylib to /usr/lib/
Change path based on wherever you put older XCode form above:

        ln -s /Applications/Xcode_511.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/lib/libatlas.dylib /usr/lib/libatlas.dylib
(could I have just copied the file to this directory, and then deleted this older XCode?)

5. compile ruby with updated gcc
I used rbenv with the ruby-build plugin; I selected an older Ruby (2.0.0-p598) so that I didn't overwrite an existing Ruby until I verified this works:

        rbenv install 2.0.0-p598

6. link cblas.h to /usr/include/:

        sudo ln -s /System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/cblas.h /usr/include/cblas.h
7. clone the NMatrix repo and get gem dependencies:

        git clone https://github.com/SciRuby/nmatrix.git
        cd nmatrix
        rbenv local 2.0.0-p598
        gem install bundler
        bundle

8. compile, package and install gem:

        bundle exec rake compile
        bundle exec rake repackage
        gem install pkg/nmatrix-0.1.0.gem

9. confirm successfull install via irb:

        irb -r nmatrix

**Comment by mohawkjohn** [comment]
This does look helpful; however, are you a member of one of the Apple Developer Programs? I don't seem to have access to XCode 5.1.1 when I login with my Apple ID.

**Comment by gbuesing** [comment]
I am a member of the Apple Developer Program. I see now that the link is protected by login, unfortunately.

I guess atlas could be installed from source? It's too bad there's no homebrew formula for it. Downloading an old XCode seems a very roundabout way to get a dependency.

**Comment by mohawkjohn** [comment]
I know. I'm an NMatrix developer and I can't actually use NMatrix. How frustrating. =/

Unfortunately, there's no way to turn off throttling on MBAs, so it's not possible to install ATLAS from source.

**Comment by gbuesing** [comment]
Could NMatrix be run on Mac OS X via a Linux virtual machine? I assume it wouldn't be as fast as a native install, but it would be much easier to get everything up and running if you could just grab a disk image.

**Comment by mohawkjohn** [comment]
I think what needs to happen is that we have to abstract out the atlas components from NMatrix and put them in a separate gem — which has been proposed as a GSoC project. Then we can work on providing other implementations for various functionalities.

**Comment by gbuesing** [comment]
That sounds good.

Until then, I guess Apple Developer Program ($99/year) is required, unfortunately.

**Comment by andrewcsmith** [comment]
I have NMatrix running on OSX 10.10, with atlas/lapack. It takes a little more work to get atlas running (and my installation is probably not optimized as efficiently as it could be), but it's totally possible. I just did it again when I wiped my hard drive clean about two months ago. Anyway, if you give it a shot and want to send me the errors (or post to sciruby list) then maybe we can fix the bugs together and write a tutorial for future generations.

**Comment by ejstembler** [comment]
Is this out of date?

    Error: No available formula for gcc49

Though, if you use just <tt>gcc</tt> it will install version <tt>gcc-4.9.2_1</tt>.  In any case, I still could not get this to install on Yosemite 10.10.2

**Comment by mohawkjohn** [comment]
Yeah, it looks like you can just do gcc instead of gcc49 now. I'm not sure why gcc49 wouldn't work — it still does for me.

**Comment by gbuesing** [comment]
Aha, looks like gcc49 is only available after you do ```brew tap homebrew/versions```.

Looks like the latest gcc formula has gfortran enabled by default: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb

**Comment by gbuesing** [comment]
I successfully installed NMatrix on my backup laptop using just ```brew install gcc`` as the first step (instead of brew install gcc49 --enable-fortran).

I've updated the steps above accordingly.

**Comment by gbuesing** [comment]
Another simplification to the process -- I tried compiling another ruby version with a simple ```rbenv install``` without the additional flags pointing to gcc et al, and NMatrix installed without error.

I've updated the instructions above. Would be great if someone else could verify that this works -- @ejstembler would you be able to give this a try?

**Comment by mohawkjohn** [comment]
Wait, you got it to install with clang? That's awesome news.

**Comment by hbcbh1999** [comment]
I'm compiling nmatrix on Yosemite 10.10.3. Is there anyway I can download xcode 5.1.1?? I'm not an apple developer. 


linking shared-object nmatrix.bundle
ld: library not found for -latlas
collect2: error: ld returned 1 exit status
make: *** [nmatrix.bundle] Error 1
rake aborted!
Command failed with status (2): [make...]
/usr/local/lib/ruby/gems/2.2.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:155:in `block (2 levels) in define_compile_tasks'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:154:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-darwin14 => compile:nmatrix:x86_64-darwin14 => copy:nmatrix:x86_64-darwin14:2.2.1 => tmp/x86_64-darwin14/nmatrix/2.2.1/nmatrix.bundle
(See full trace by running task with --trace)

**Comment by yoongkang** [comment]
Is ATLAS the only thing preventing a build on Yosemite at the moment? 

If so has anyone tried to build ATLAS from source? If not I'll take a crack, and maybe update the docs.

**Comment by hbcbh1999** [comment]
Just realized this post is about compiling nmatrix on Yosemite, which I
posted months ago. It's pretty easy. We don't need Xcode5.1.1. Just google
Atlas package and compile it first then nmatrix. Everything will be
straightforward.

On Wed, May 6, 2015 at 11:50 PM, Yoong Kang Lim <notifications@github.com>
wrote:

> Is ATLAS the only thing preventing a build on Yosemite at the moment?
>
> If so has anyone tried to build ATLAS from source? If not I'll take a
> crack, and maybe update the docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SciRuby/nmatrix/issues/319#issuecomment-99703062>.
>



-- 
Hao Zhang
Dept. of Applid Mathematics and Statistics,
Stony Brook University,
Stony Brook, New York, 11790

**Comment by mohawkjohn** [comment]
Actually, compiling ATLAS correctly on MacBooks is nontrivial. No obvious
way to turn off processor throttling. If someone could find out, that would
be awesome.

**Comment by agarie** [comment]
Expanding on John's comment: the problem with ATLAS on a MacBook is not that you can't compile & install it, this is totally possible. The real problem is that you can't turn off processor throttling, so the optimization step of the installation isn't trustworthy. (at least from what I remember, it's been a *long* time since I tried installing ATLAS on my MBP)

If you aren't interested in performance right now and just want to have a working NMatrix to test the gem, there shouldn't be any problem in this procedure. In fact, it'd be nice to have it written up in the wiki. :)

**Comment by mohawkjohn** [comment]
Agreed! It'd be lovely to have some instructions.

**Comment by gbuesing** [comment]
These instructions are no longer needed - NMatrix as of version 0.2.0 installs easily on Yosemite.
