### ISSUE TITLE
Support for C-type nan or inifinity.

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#321]
Currently if one is to create an `NMatrix` with missing data, the underlying implementation has to be of type `:object` because the NMatrix C-types don't support missing data as of now.

For example:

``` ruby

n = NMatrix.new([6], [1,2,3,nil,4,nil], dtype: :object)
```
As far as I can see in numerical analysis of data, missing data is an integral part of any research and storing the entire NMatrix as super-heavy Ruby Objects if one encounters one `nil` in a millon-sized NMatrix does not seem justified. I've seen far too many examples while working on [daru](https://github.com/v0dro/daru), where users load CSV data with say a few thousand rows and one or two of the rows are missing, which forces the entire storage to shift to Ruby Objects instead of the more efficient `ints` or `floats`.

Therefore to address this problem, I suggest we add support for C-type `nan` or `infinity` which can be potentially useful in handling missing data. So for example, a user will be able to create an NMatrix like:

``` ruby

n = NMatrix.new([5],[1,2,3,4,nil], dtype: :int32)
```
...and the `nil` would be parsed as a C-type `nan` (or `infinity`). Of course matrix operations would be rendered useless in this case, but when using NMatrix predominantly for storage (like in daru), this would be indispensable.

To top it all, since one of the immediate objectives of NMatrix is to separate the linear algebra (ATLAS etc.) and other future math bindings into a separate gem, I dont think loss of some matrix methods would be regrettable. Of course the user can fill in whatever numerical value she wants into the missing data at a later stage if she so desires, and also use some specialized functions for dealing with matrices with missing data.

[This](http://stackoverflow.com/questions/1923837/how-to-use-nan-and-inf-in-c) has some great insights on representing `nan`s in C.

Numpy also supports missing data through its `NaN` data type and I think supporting this in NMatrix would be a logical next step. They've written a nice article on the methodology and approach over [here](http://www.numpy.org/NA-overview.html), and a tutorial for dealing with missing data can be found [here](http://nbviewer.ipython.org/github/rasbt/python_reference/blob/master/tutorials/numpy_nan_quickguide.ipynb).

**Comment by mohawkjohn** [comment]
Nan/infinity is important, but it's part of the floating point specifications, not integers. And NMatrix *does* support Nan/infinity for :float32 and :float64.

**Comment by v0dro** [comment]
This throws an error:

``` ruby

n = NMatrix.new([5],[1,2,4,nil,nil], dtype: :float32)
# TypeError: no implicit conversion to float from nil
# from (pry):2:in `initialize'

```

How does one initialize an NMatrix with missing values?

My bad, it should be floats not integers.

**Comment by agarie** [comment]
Try `Float::NAN` or `Float::INFINITY` instead of `nil`.

If I understand correctly, you're suggesting a way to initialize a NMatrix with a Ruby array (e.g. `[1, 2, 4, nil, nil]`) in order to generate `N[[1.0, 2.0, 4.0, Float::NAN, Float::NAN]]`, right? As far as I know, there isn't such a setup right now.

**Comment by mohawkjohn** [comment]
@agarie is correct.

I would not support re-interpreting nil to mean something else, as it would result in unexpected behavior.

**Comment by v0dro** [comment]
Ah I wasnt aware of that. Thank you.

IMO we should update the wiki's to reflect the fact that NaN is supported in this manner!

**Comment by mohawkjohn** [comment]
So go update it. =)

**Comment by v0dro** [comment]
But it so happens in real life that if you have a data file (say CSV), ruby will typically read that as `nil`, and you'll end up storing as an `:object` array. Storing as `NaN` will require undue and inefficient post-processing on the user's part.

Given this, won't it make sense to interpret `nil` as `NaN` if the rest of the data is also floating point? 

Oh and, support for integer `NaN` would also be great in the future. For example, for storing date time indexes (which are typically 64 bit timestamps), and you encounter missing values.

**Comment by mohawkjohn** [comment]
That's a problem with the CSV library, not with NMatrix. Fix it in CSV.

Storing an integer NaN would result in losing a bit of capacity for integer. Not worth it, because that means a whole range of numbers won't be available any longer.
