### ISSUE TITLE
Unsigned integers and string data types for NMatrix?

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#322]
It would be great if NMatrix could serve as a Ruby interface to C-type character limited strings and unsigned integers or floats.

For example, to use nmatrix to store some strings values obtained from a database:

``` ruby

n = NMatrix.new([2,1], ['AAPL', 'GOOG'], dtype: :str4)
```
This will store the strings as 4 character C-type strings.

It would be especially useful when CLAPACK functions are abstracted from nmatrix and people want to use it as an efficient container for data.

**Comment by mohawkjohn** [comment]
This should already be doable, using `dtype: :object`. Adding and removing types is decidedly non-trivial, and there's no obvious way to make it easier. Furthermore, adding types increases compile time substantially.

**Comment by v0dro** [comment]
But the whole point of having an efficient C level data store is lost if you end up storing objects!

Ruby strings are VERY inefficient when it comes to storage. This is the reason why I'm suggesting using structs for handling the data types. NMatrix would become very scalable if that is done.

**Comment by cjfuller** [comment]
That doesn't quite make sense to me.  What general-purpose optimized C operations do people want to do on multidimensional arrays of strings?  I can't think of any (not that that means there aren't any...), and certainly none of the matrix math operations make sense.

In that case, the operations will have to be written in ruby, and there's additional overhead of encoding back and forth between ruby and C strings.  Then, if you have operations you need to do on all the strings together, you will end up making two copies of them, which is worse, or if you only need to operate on some of the strings, it would almost certainly be more (memory) efficient to read them lazily from a file and process them in pure ruby that way.

I don't understand the goal of having a general-purpose C-level data store if you have to convert it back and forth to ruby any time you need to do anything -- that's not efficient.
