### ISSUE TITLE
Dropping support for Rational data types

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#323]
Rational data types are not supported by any of the major C scientific libraries and I think they're a major source of bloat in the nmatrix code because they need their own implementation of CLAPACK functions.

Considering that Rationals can be stored as the nmatrix `:object` dtype, what do you guys think about dropping support for rationals? Is it really worth the effort to support rationals when most math operations don't support them by default?

**Comment by mohawkjohn** [comment]
I'm fairly sure there's already an issue open for this.

**Comment by v0dro** [comment]
Cant see any open. But I think I remember someone posting on the mailing list about it once.

**Comment by mohawkjohn** [comment]
I think that yes, we should probably remove these types. I worry that they're too susceptible to overflow.

I think when they get removed, we should also make a point of adding any other types we think people might want — like float128, if that's something that interests people.

**Comment by v0dro** [comment]
I'd say unsigned and C strings.

**Comment by wlevine** [comment]
I got fed up with rationals and accidentally started working on this. I removed all the rational stuff from the C/C++ code but I haven't touched the ruby code or specs, so I'm not sure if it works yet. On my machine it speeds up compilation from about 3 minutes to 2 minutes. Just thought I should check that we still want this before spending any more time.

**Comment by mohawkjohn** [comment]
Yes. But you may have bitten off more than you can chew.

**Comment by v0dro** [comment]
That's great!!

Can you replace the rationals with unsigned int/float types? That would be very VERY helpful. Later maybe I can implement a datetime extension (#382) using a unsigned int64 data type.

By the way, will it also be possible to design a better implementation for the data type system? Its currently only stored as an enum, and adding new types is a big pain. Can we think of a class-based system like numpy?

**Comment by mohawkjohn** [comment]
That's an entire GSoC project. Someone would really have to propose it themselves, too, because off the top of my head I'm not sure how you'd do it.

**Comment by agarie** [comment]
That's great, Will. I think that *dropping* support should be easier than adding it, so I guess you can do it right now. 

By the way, I support rewriting the dtype system, but as John said, it needs a bit more work before we can conclude how it should be done.

**Comment by mohawkjohn** [comment]
Fixed by https://github.com/SciRuby/nmatrix/pull/383
