### ISSUE TITLE
Bug when including "nmatrix.h"

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#324]
I'm trying to write an nmatrix extension using the C API but I get an error `/home/sameer/.rvm/gems/ruby-2.1.0/gems/nmatrix-0.1.0/../../extensions/x86-linux/2.1.0/nmatrix-0.1.0/nmatrix.h:249:1: error: unknown type name ‘STORAGE’` and `/home/sameer/.rvm/gems/ruby-2.1.0/gems/nmatrix-0.1.0/../../extensions/x86-linux/2.1.0/nmatrix-0.1.0/nmatrix.h:381:3: error: unknown type name ‘NMATRIX’`.

You can see the code [here](https://github.com/v0dro/scratch/blob/master/ruby_c_exp/ctest/ext/ctest/ctest.c#L2).

**Comment by v0dro** [comment]
@mohawkjohn any idea on this? I checked SciRuby/rb-gsl and it seems to be working there.

**Comment by v0dro** [comment]
I just figured this out.

The problem was that macros when compiling with a C compiler (i.e. `__cplusplus` undefined) were prefixed with `NM` which led to a discrepancy.

So if a function said `STORAGE *`, and if the extension was compiled with a C compiler, the macro would actaully be `NM_STORAGE`. 

I'm sending a PR in a minute.

**Comment by cjfuller** [comment]
This is not a bug; we're deliberately putting on the NM prefix as a workaround for C's lack of namespacing.  See the comment starting at nmatrix.h:88.

My guess is that you're seeing compilation problems because you're accidentally compiling one of the C++-only sections of NMatrix with a C-only compiler.

**Comment by v0dro** [comment]
No I'm including `nmatrix.h` in a C file, C++ has nothing to do over there.

Might it be because of that? So now if I want to use it, do I need to keep `nmatrix.h` in a C++ file, and then call functions defined there from a C file?

**Comment by cjfuller** [comment]
Ok, sorry, misunderstood what you were trying to do.  Thought you were trying to compile some extra stuff in with NMatrix.

That would be one poossible approach.  I'll need to look at it a little more why this isn't working.  I thought I had done this same thing at some point.

It may be that nmatrix.h:184 needs an NM_ prefix and the stuff at the bottom too, but I think things would have been more broken if that were universally the case...  (In any case, removing the namespacing in the PR is not the solution we want.)

Will investigate.

**Comment by v0dro** [comment]
We can alternatively selectively compile the entire file with `NM_` wherever necessary if a C compiler is found.

**Comment by mohawkjohn** [comment]
Selectively compile which file? The difficulty with `nmatrix.h` is that it's used both internally (by NMatrix) and externally (by other libraries accessing NMatrix's definitions).

@cjfuller is being cautious because he and I have *both* messed up this file before. =)

**Comment by v0dro** [comment]
Selectively compile `nmatrix.h`, i.e if it is included in a C file and only a C compiler is being used, all the functions at the bottom will use macros `NM_STORAGE` and `NM_NMATRIX` instead of the `STORAGE` and `NMATRIX` that they use now.

Oh and by the way, those macros are written differently as `NM_STORAGE` and `NM_NMATRIX` for C, but thorughout the whole codebase its only `STORAGE` or `NMATRIX`. Theres not a trace of `NM_STORAGE` or `NM_NMATRIX` anywhere in the code.

Moreover. including `nmatrix.h` is becoming very complicated because I first need to include and use it in a `cpp` file and then write C accessors so that I can access those functions from C. I havn't been able to set up a working extension yet, after trying for ~6 hours, because it involves too much reading up of `mkmf` selective compilation and all sorts of things. 

Alternatively, we can completely separate the internal and external API's that are exposed by `nmatrix.h`. The external one will have _only_ C macros whereas the interal one can keep both, or something like that.

**Comment by cjfuller** [comment]
> Oh and by the way, those macros are written differently as NM_STORAGE and NM_NMATRIX for C, but thorughout the whole codebase its only STORAGE or NMATRIX. Theres not a trace of NM_STORAGE or NM_NMATRIX anywhere in the code.

Yes, because NMatrix is mostly written in c++ and therefore requires a c++ compiler, which will use non-NM_ versions.

**Comment by v0dro** [comment]
Thank you!

And the way you've solved it is interesting.
