### ISSUE TITLE
Allow storing matrices in row major or column major form

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#344]
Most numerical libraries being in FORTRAN, conversion to column major form is needed to send data into the matrix.

If NMatrix could support an attribute that gave an idea if the storage is in row major or column major form, users can directly specify data in col-major form and avoid transposing values each time a FORTRAN-derived function is called (like CLAPACK). Of course this can still be done if one just specifies their matrix values in column major format, but having an explicit instance variable like `@row_major = true OR false`holding that information and making it explicit would be great.

Calling LAPACK/BLAS functions without specifying whether row/column major explicitly in the function would simplify calling those methods too.

To demonstrate, for creating a column-major matrix:

``` ruby
n = NMatrix.new([3,3], [1,4,7,2,5,8,3,6,9], row_major: false)
```

The default can be `row_major: true`. This can also be stored as a single boolean value in the C code for efficiency.

Further, methods for converting between row and column major can be added (which toggle the `row_major` value appropriately).

OR maybe we can always store in row major mode and allow people to only _view_ data in column major (like [numpy](http://stackoverflow.com/questions/20341614/numpy-array-row-major-and-column-major)). That would set a compulsory default to row major and will avoid checking the value of `row_major` every time a function call depending on the storage order is to be made.

**Comment by mohawkjohn** [comment]
Adding such an option would dramatically complicate a lot of methods that depend on storage order. I'm inclined to mark this wontfix.

**Comment by v0dro** [comment]
So I'm also suggesting that column major can just be a 'view' into the data, not the way the data is actually stored. Wont this make things simpler?

**Comment by mohawkjohn** [comment]
Could you possibly reuse the reference slice code to accomplish this? Those are basically views.

**Comment by v0dro** [comment]
Will check it out and get back to you.

**Comment by mohawkjohn** [comment]
The more I think about this, the more I think it creates a lot of work for not very much gain. Feel free to argue with me. :)
