### ISSUE TITLE
(NMATRIX)-> count is never set to actual number of elements in the nmatrix

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#356]
The main nmatrix data structure contains [an element called 'count'](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/nmatrix.h#L152) which is supposed to store the total number of elements in an NMatrix.

It so happens, that once the `count` struct element is set to `1` in [` nm_dense_storage_create_dummy`](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/storage/dense/dense.cpp#L205), it is never set to the actual number of elements that are present in the nmatrix, and hence the `count` element remains set a `1` irrespective of the number of elements present in the matrix.

One might argue that `NMatrix#count` works, but thats only in the ruby API and that too because the `Enumerable` ruby module has been included in the NMatrix class. The C API still malfunctions.

**Comment by cjfuller** [comment]
Oh, bah, that's totally my fault, sorry.  That should be:
`s->count = nm_storage_count_max_elements(s);` at `dense.cpp:216`.  Not sure what I was thinking...

Will fix.

**Comment by v0dro** [comment]
We can also add a function `NMatrix#count` which retrieve `s->count` instead of relying on `Enumerable#count`. Should be faster.

**Comment by cjfuller** [comment]
Hmm, maybe that's actually a recipe for segfaults, and count should mirror what's in elements.  Going to set count to 0 in `nm_dense_storage_create_dummy`, and then update to the correct count in `nm_dense_storage_create` instead.
