### ISSUE TITLE
complex_conjugate (non-bang) version in C is broken

### ISSUE THREAD

**Issue by cjfuller** [SciRuby/nmatrix#358]
We define `complex_conjugate` (no exclamation) both in `ruby_nmatrix.c` and in `math.rb`.  The one defined in ruby overwrites the C version, so the C version is untested.

The C version uses an uninitialized variable for the destination NMatrix and is totally broken.  We should either remove it, or fix it and remove the ruby version.

**Comment by yoongkang** [comment]
We can close this due to #401.
