### ISSUE TITLE
nmatrix extension to support math on matrices with missing data

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#359]
Say I have an NMatrix: 
``` ruby

n = NMatrix.new([3], [1,2,Float::NAN]. dtype: :float64)
```

Currently calling `n.mean` produces `NAN`. It would be great if an optional extension could be created (after @wlevine's project is done) for producing meaningful output by skipping the `NAN`, wherever it occurs in the vector.

**Comment by mohawkjohn** [comment]
You can always just monkey-patch `mean` in whatever code you wanted the different behavior in.

**Comment by v0dro** [comment]
Why not create an optional extension (or plug-in) that will implement certain algorithms differently? I'm saying put this in the mainline nmatrix code.

The scope of the code will increase manifold.

**Comment by mohawkjohn** [comment]
That's what a monkey patch is.

**Comment by v0dro** [comment]
What I'm saying is, have an official nmatrix extension, like nmatrix-lapacke is going to be. Not specific to a particular library.

**Comment by mohawkjohn** [comment]
Anyone can write this, but what would be the design philosophy of such a gem?

**Comment by v0dro** [comment]
I'm not sure I completely understand what you mean. Are you talking about usage scenarios?

**Comment by mohawkjohn** [comment]
Okay, let's do a thought experiment. I create a gem called nmatrix-nanless. In the gem summary, I say, "NMatrix monkey patches which ignore NaN in all statistical calculations because NaN sucks."

Or would I say, "NMatrix monkey patches which make some arbitrary changes to NMatrix which you'll just have to read the code to understand," and call it nmatrix-readthecode?

How would you sum up what this feature set does in one sentence?

**Comment by v0dro** [comment]
"Statistical and arithmetic algorithms for NMatrix for dealing with missing data"

**Comment by mohawkjohn** [comment]
NaN is *not* missing data.

**Comment by agarie** [comment]
You can represent missing data in a few ways, e.g. using a specific object (`Object.new`?) or even NaN. I think Pandas uses `numpy.nan` as its Not Available (NA) value; I have no idea about R.

If I remember [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point) correctly, NaN has some bits that can be used as a "payload", meaning you can encode some information in it. Thus it should be possible to define a NaN different than the one used in Ruby's `Float::NAN`, and this knowledge could be used in floating-point matrices.

What do you folks think about defining `NMatrix::NA` for representing missing values? I can take a closer look at the specification to discuss this idea later; right now I'm kind of in a hurry.

**Comment by v0dro** [comment]
That's what NaN is treated as in most of the applications that I've come across! (pandas - as Carlos points out - for example). I'm just being specific about NaN because that's what I usually come across in most of the data crunching code that I've written.

I agree that NaN is not _always_ treated as missing data and any other value can be potentially treated as missing (for example `nil` or an arbitrary string or symbol), but I'm sure we can potentially accommodate for that when coding this extension.

And I am in favor of `NMatrix::NA`. That would be a cool new feature and would really be a step forward in opening up nmatrix to tasks other that numerical storage and linear algebra.

**Comment by mohawkjohn** [comment]
If you can find a way to encode `NMatrix::NA` on `NaN`, I say go for it. But I don't want to introduce a behavior that is counter-intuitive just because NumPy does it.

**Comment by agarie** [comment]
`NMatrix::NAN` shouldn't be confused with "having functions that ignore NAN values". I also think that we shouldn't have this behavior in NMatrix. :-)

I think we should have a library for data analysis (hint: daru) that implements this behavior on top of NMatrix. This seems the saner option.

**Comment by mohawkjohn** [comment]
Yes. I'd also point out that totally changing the behavior of methods in one library by inclusion of another is something that many Rubyists recommend against. It's a reason people don't like monkey patches. Obviously we ignore that "rule" a lot, but it's still worth keeping in mind.
