### ISSUE TITLE
Searching for nmatrix.h on Travis CI

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#364]
I'm trying to get [gsl-nmatrix](https://github.com/v0dro/gsl-nmatrix) to test properly on this [Travis build] (https://travis-ci.org/v0dro/gsl-nmatrix/jobs/64093509), but the build fails every time because `Gem::Specification.find_all_by_name` is [unable to load the require paths of nmatrix.h](https://travis-ci.org/v0dro/gsl-nmatrix/jobs/64093509#L273).

I tried using `Gem::Specification.find_by_name`, `.find_by_path` etc. to no avail. Bear in mind that Travis reports that [it IS using nmatrix from source ](https://travis-ci.org/v0dro/gsl-nmatrix/jobs/64093509#L192). Any ideas how this can be made to work? Maybe set `Gem::Specification#require_path=` manually in the nmatrix spec?

**Comment by blackwinter** [comment]
Since you switched to Bundler, you need to use `bundle exec rake` instead of `rake` in your `script` setting. In the current form, `Gem::Specification.find_by_path` doesn't know about Gems installed through Bundler.

**Comment by v0dro** [comment]
Ok that worked thanks!
