### ISSUE TITLE
Prepare the next release

### ISSUE THREAD

**Issue by agarie** [SciRuby/nmatrix#367]
Hey folks, we need to have a clear roadmap for the next release (be it 0.1.1 or even 0.2.0). A checklist with the necessary steps (e.g. see last pull requests/issues and update History.txt, pending issues) should be enough. A deadline would be even better.

Any ideas?

**Comment by mohawkjohn** [comment]
I keep wanting to do a release but then we find a new major bug.

**Comment by agarie** [comment]
I see, but we should at least specify a set of issues that must be solved before release. How about: #358, #360, #373 and #374. What do you think?
