### ISSUE TITLE
Parallel builds for nmatrix

### ISSUE THREAD

**Issue by wlevine** [SciRuby/nmatrix#369]
I think this would be nice to have. Presumably all you would need to do is have rake invoke `make -jN` instead of `make`, but I haven't figured out how to do that.

**Comment by mohawkjohn** [comment]
This might be one to ask of the Rake people, or possibly even Ruby-core since that's who maintains extconf.rb.

**Comment by wlevine** [comment]
The rake folks suggest using `MAKE="make -j8" rake ...`: rake-compiler/rake-compiler#114

That seems good enough for me. We probably don't want this by default (unless our build times get way longer), so I'll close this issue.

**Comment by agarie** [comment]
Did you test it locally, @wlevine? If this really cuts down the build time, we should suggest it on the installation guide. :+1:

**Comment by wlevine** [comment]
On my machine it cuts the build time in half from ~3 min to ~1.5 (with -j4). You don't get a full 4x speedup because there are one or two files that take way longer to compile and so by the end of the build some of the cores are idle.

I also checked that the same trick works when building with `gem install`, so that's good to know also.
