### ISSUE TITLE
Developement version of NMatrix bloats RAM

### ISSUE THREAD

**Issue by agisga** [SciRuby/nmatrix#377]
I have traced some bad memory behavior of my mixed models gem to some recent updates of NMatrix (though I don't know which ones exactly). 

Here is a simple memory usage comparison between the newest development version of NMatrix and the NMatrix gem (which is an older version). I ran the following code on both versions. Results below.

```Ruby
require 'nmatrix'

def get_memory_usage
  `ps -o rss= -p #{Process.pid}`.to_i
end

before = get_memory_usage
puts "BEFORE: #{before}"

1000000.times { a = NMatrix.random([10,10], dtype: :float64) }

after = get_memory_usage
puts "AFTER: #{after}"
puts "AFTER-BEFORE: #{after - before}"
```

With the NMatrix gem, I get:

```
alexej@Imaging-Genomics-Tower-Precision-5810:~$ ruby test.rb
BEFORE: 12784
AFTER: 18588
AFTER-BEFORE: 5804
```

With the most recent development version of NMatrix, I get:

```
alexej@Imaging-Genomics-Tower-Precision-5810:~$ ruby test.rb
BEFORE: 12980
AFTER: 1088252
AFTER-BEFORE: 1075272
```

Additionally, computing `a.det` inside the `for` loop consumes twice as much memory under the NMatrix development version, but not with the NMatrix gem. Defining `a` outside of the `for` loop has no effect on the memory consumption.

This is a very serious issue for me, because it makes my mixed models gem practically not functional (except for the simplest models), but I have absolutely no idea what's wrong.

**Comment by mohawkjohn** [comment]
@agisga Can you run a `git bisect` between the two versions and see if you can track down a specific commit?

**Comment by agisga** [comment]
`git bisect` says:
(a66a790247e94f1ba13dc1dfea11497f6267db20](https://github.com/SciRuby/nmatrix/commit/a66a790247e94f1ba13dc1dfea11497f6267db20) is the first bad commit

Maybe somebody can confirm that there is a problem and that it's not somehow specific to my system.
(`git bisect` is really neat!)

**Comment by wlevine** [comment]
I see the same problem.

**Comment by cjfuller** [comment]
Oh, bah.  I see what the problem is.  That's a reference count and not actually an element count, so when I changed it that means that we no longer free the underlying storage.  Terrible name choice on my part, since there's also a local variable named count that's the element count.  Feel free to `git revert` that commit.

**Comment by cjfuller** [comment]
Also cc @v0dro, since you're probably relying on that being an element count and not a reference count (as seen in #356).
