### ISSUE TITLE
internal implementation of cblas_nrm2 is broken for complex types

### ISSUE THREAD

**Issue by wlevine** [SciRuby/nmatrix#389]
```
> x = NMatrix.new([4,1], [2,-4,3,5], dtype: :float64)
> NMatrix::BLAS.nrm2(x, 1, 3)
=> 5.385164807134504
> x = NMatrix.new([4,1], [2,-4,3,5], dtype: :complex128)
> NMatrix::BLAS.nrm2(x, 1, 3)
=> 4.0
```

https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/math/nrm2.h

The ATLAS version works fine.

**Comment by lokeshh** [comment]
The bug gets fixed if I pass `ssq` instead of `temp` in [this line](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/math/nrm2.h#L145). 

Any idea where can I find documentation of this function?
