### ISSUE TITLE
Possible duplication between solve and clapack_getrs

### ISSUE THREAD

**Issue by wlevine** [SciRuby/nmatrix#390]
We have a function called `__solve__` and also an internal implementation of `clapack_getrs`. At a quick glance, they both seem to do the same thing. John, do you remember if there is any difference between these or any reason to prefer one over the other?

**Comment by mohawkjohn** [comment]
I think `__solve__` is supposed to call whichever implementation is available, isn't it?

https://github.com/SciRuby/nmatrix/blob/744b2e185ef774e7e86827ca89167b1c4d75a6de/lib/nmatrix/math.rb#L266
^ that calls `__solve__`.

**Comment by wlevine** [comment]
This is the implementation of __solve__: https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/math.cpp#L243

It takes an LU factorized matrix equation and solves it. Which seems the same as clapack_getrf: https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/math/getrs.h

**Comment by mohawkjohn** [comment]
Yeah, I think it's a dup. Who submitted it?

**Comment by wlevine** [comment]
Oh, it was @v0dro. Any thoughts, @v0dro?

**Comment by v0dro** [comment]
I wanted to put an ATLAS/LAPACK independent function for solving equations in nmatrix. That's why I submitted `#solve`.

**Comment by wlevine** [comment]
`#solve` is good. I was wondering about `__solve__`, which seems to duplicate `clapack_getrf`, which (despite its name) is part of the nmatrix core and not any external library.

**Comment by mohawkjohn** [comment]
We may have renamed it with the underscores after @v0dro wrote his method, just so the old one would still be available.

**Comment by v0dro** [comment]
@wlevine  it's probably a duplicate then.

**Comment by wlevine** [comment]
Fixed in #393. I removed `__solve__` and made `#solve` call `clapack_getrf`
