### ISSUE TITLE
Add Magdalen's FFTW as an NMatrix extension

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#397]
@thisMagpie's last year's GSOC project (https://github.com/thisMagpie/fftw) has not seen active use yet.

Maybe adding this to nmatrix like ATLAS and LAPACKE would be great. I think most of the work regarding interfacing nmatrix with FFTW is almost done (though I do have some opinions about the way the nmatrix C API has been used).

WE can then release this as nmatrix-fftw.

**Comment by mohawkjohn** [comment]
@v0dro Would you like to take this on?

**Comment by v0dro** [comment]
Sure! In a few weeks.

**Comment by v0dro** [comment]
I'm doing this. Will send my plan on the mailing list in some time.

**Comment by v0dro** [comment]
See my progress on this branch: https://github.com/v0dro/nmatrix/tree/nmatrix-fftw

Will send a PR soon.
