### ISSUE TITLE
Question: NMatrix#concat is a little confusing.

### ISSUE THREAD

**Issue by yoongkang** [SciRuby/nmatrix#402]
Hi, I'm trying to use #concat to join two matrices and am a little confused. Maybe this is something to add in the docs...

```ruby
require 'nmatrix'

a = NMatrix.zeros([3, 1])  # => [ [0.0] [0.0] [0.0] ]
b = NMatrix.zeros([3, 2])  # => [ [0.0, 0.0] [0.0, 0.0] [0.0, 0.0] ]

a.concat(b) # => [ [0.0, 0.0, 0.0] [0.0, 0.0, 0.0] [0.0, 0.0, 0.0] ]

b.concat(a) # => RangeError: slice is larger than matrix in dimension 1 (slice component 2)
```

We're concatenating a 3x2 matrix and a 3x1 matrix. Shouldn't this just create a new 3x3 matrix of zeroes in either case? I expected `b.concat(a)` to simply add a column to `b`.

Also:

```ruby
require 'nmatrix'

c = NMatrix.new([1, 3], [1, 2, 3])
d = NMatrix.new([1, 3], [4, 5])

c.concat(d) # => RangeError
d.concat(c) # => [ [4, 5, 1, 2, 2] ]
```

Am I misunderstanding `#concat`?

**Comment by mohawkjohn** [comment]
Please see this old forum post about concat for some background:

https://groups.google.com/forum/#!searchin/sciruby-dev/concat/sciruby-dev/FVmOr3czsik/iJKE29rbpqQJ

It's definitely confusing. There's not really a simple way to do it.
