### ISSUE TITLE
undefined variable in extconf.rb

### ISSUE THREAD

**Issue by agisga** [SciRuby/nmatrix#403]
The variable `idefaults` is used but never defined in [nmatrix_lapacke/extconf.rb](https://github.com/SciRuby/nmatrix/blob/b7d367f544a9d48af5f1b9dedb7ef6adcf488091/ext/nmatrix_lapacke/extconf.rb#L169)

Should `idefaults[:lapack]` in the referenced line be set to `nil` or something like `/usr/include/lapack`?

**Comment by wlevine** [comment]
Good catch. I think we can just replace that argument with an empty array for now. For nmatrix-lapacke, I think all the header files we need are available locally in the repository. Most of that file is just copied from the original extconf.rb and it could probably be cleaned up quite a bit, but I'm afraid to touch it too much.

**Comment by mohawkjohn** [comment]
Fixed by #404
