### ISSUE TITLE
Change README to GitHub flavored markdown

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#414]
The README is currently like an `rdoc` document and kind of annoying to modify.

Changing to `.md` and making necessary changes for supporting GitHub flavored markdown should simplify things further.

**Comment by mohawkjohn** [comment]
See also #56. Also, RDoc is our priority, so if you can get Github-flavored md to work properly with RDoc, go for it — but we switched to RDoc from md ages ago because md was insufficient.

**Comment by mohawkjohn** [comment]
Let me know if you want to re-open.

**Comment by v0dro** [comment]
Well I would personally favor markdown over RDoc any day for README files, given it's simplicity and speed of typing. 

If you still want to keep RDoc for the README, let this be closed.
