### ISSUE TITLE
transpose swallows argument

### ISSUE THREAD

**Issue by firemind** [SciRuby/nmatrix#416]
Matrix#transpose seems to take an argument without using it. This leads to behavior that is very non-intuitive when multiplying the result by a number and omitting the space between * and the variable.

I realize omitting the space is wrong in the first place but having transpose swallow arguments makes things a lot harder to debug. Is there a reason for having it take arguments?

Here is an example.

```ruby
require 'nmatrix'

m = N.new [5,1], [0.013256708021555484, 0.013170708775568673, 0.01301026646071902, 0.013049531157433895, 0.015499716459018048]

puts m.transpose * 0
puts m.transpose *0
```

Output:

```
[0.0, 0.0, 0.0, 0.0, 0.0]
[0.013256708021555484, 0.013170708775568673, 0.01301026646071902, 0.013049531157433895, 0.015499716459018048]
```

**Comment by mohawkjohn** [comment]
Yes. It's for matrices that are more than two dimensions — you have to know which dimensions you're transposing.

**Comment by firemind** [comment]
Oh, I see now. The docs are pretty clear about it too now that I look at them again. Sorry about that. I seem to have mixed up the source files for NMatrix and the stdlib ruby Matrix which is why I thought there wasn't supposed to be an argument.

So apparently the permute argument is never used if the matrix that is being transposed is one or two dimensional. Which is why it didn't matter that I passed a bogus value.

Might I propose reordering the argument check to something like this to prevent invalid arguments from being swallowed silently?

```ruby
if permute.nil?
  if self.dim == 1
    return self.clone
  elsif self.dim == 2
    new_shape = [self.shape[1], self.shape[0]]
  else
    raise(ArgumentError, "need permutation array of size #{self.dim}")
  end
elsif permute.sort.uniq != (0...self.dim).to_a
  raise(ArgumentError, "invalid permutation array")
else
  # Figure out the new shape based on the permutation given as an argument.
  new_shape = permute.map { |p| self.shape[p] }
end
```

**Comment by mohawkjohn** [comment]
I think that'd be a great idea. Feel free to submit a pull request!
