### ISSUE TITLE
Release new nmatrix and plugins

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#434]
Recent changes have added lots of new functionality and made nmatrix compatible with ruby 2.3.

I think it's time to release nmatrix 0.3.0. @mohawkjohn thoughts?

**Comment by mrkn** [comment]
Releasing the new version of gem will resolve some issues on osx.
I'm the one of those who need the new release for development some gems depending on nmatrix.

**Comment by v0dro** [comment]
Yeah, and I also need the new version for the latest release of daru.

**Comment by mohawkjohn** [comment]
@v0dro Can you compile all of the changes since the last version into the History.txt file, and update the manifest (see rake check_manifest also)? Send me a pull request, I'll check it over, and I'll try to push the new gem today. Sorry, swamped at work. Otherwise won't get to it until Monday.

**Comment by v0dro** [comment]
On it. Will send it through in a few hours.
