### ISSUE TITLE
Adding a simple function for Adjugate matrix 

### ISSUE THREAD

**Issue by Arafatk** [SciRuby/nmatrix#439]
I was looking through the nmatrix  and i could not find a function to return  the adjugate matrix of a given matrix. I was wondering if adding this would be of interest to the library. 
I would be willing to make a pr for this and  add  documentation,tests. 
@v0dro @mohawkjohn Please take a look.
Thanks

**Comment by mohawkjohn** [comment]
Can you offer any ideas as to what calculation of the adjunct would be useful for?

**Comment by Arafatk** [comment]
@mohawkjohn  Adjugate matrices are  rarely used in matrix operations(eg jacobi's formula).But they could still be used as an additional  function.Its easy to add an adjugate matrix function  as matrix inverse and matrix determinant are already present in nmatrix.

**Comment by mohawkjohn** [comment]
I don't think those are the most efficient ways to compute inverse and determinants, though. I'd suggest looking through a book like _Matrix Computations_ by Golub and seeing what else is worth implementing. A key goal should be to provide methods that people want/need to use, and we're still missing a few of those.

**Comment by Arafatk** [comment]
@mohawkjohn I was thinking of Qr Decomposition as its present in many libraries and could be useful for a lot of things.It might take me quite some time to implement.
