### ISSUE TITLE
QR factorization

### ISSUE THREAD

**Issue by agisga** [SciRuby/nmatrix#440]
- QR factorization is one of the most widely used matrix decompositions.
- NMatrix currently does not have a QR factorization method (please forgive me if I'm wrong :) ). 
- QR factorization is implemented in the LAPACK function [dgeqrf](http://www.netlib.no/netlib/lapack/double/dgeqrf.f), or maybe even better QR with column pivoting as implemented in [dgeqp3](http://www.netlib.no/netlib/lapack/double/dgeqp3.f). I think that might be a starting point.

**Comment by v0dro** [comment]
I'm currently working on making the QR methods in [rb-gsl](https://github.com/SciRuby/rb-gsl) work with NMatrix. Will update you soon.

**Comment by agisga** [comment]
Great! 

However, I think it would be more convenient to have a QR method in nmatrix-lapacke (or nmatrix-atlas) as well. Unfortunately I am too busy for the next two month, but I will give it a try after that if nobody else does it before.

Also, once a QR method is available in NMatrix, an efficient least squares solver can be implemented in just a few lines of code.

**Comment by v0dro** [comment]
Yep. I'll put in some wrappers inside another `nmatrix-gsl` wrapper that I'm planning to make that will make use of GSL QR decomposition and will be easily callable on NMatrix objects. I think it should suffice until the ATLAS functions are exposed.

**Comment by aelnouby** [comment]
@agisga i understand now that we need to plug in the implemented dgeqrf/dgeqp3 of LAPACK in NMatrix , i noticed in [numpy.linalg.qr](https://github.com/numpy/numpy/blob/master/numpy/linalg/linalg.py#L1481) ,this is the approach used as well.

Can you help me find an example where we plugged in a LAPACK function (i don't what are the steps to do such a task) , a guide or an example will be extremely helpful.

**Comment by v0dro** [comment]
See the CONTRIBUTING.md file for all those details.

**Comment by gau27** [comment]
I was able to get `dgeqrf` working, however there really is no Q matrix output as the LAPACK [subroutine](http://www.netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational.html#ga3766ea903391b5cf9008132f7440ec7b) sort of packs the matrix into a triangular matrix and an array. 


```
         On exit, the elements on and above the diagonal of the array
          contain the min(M,N)-by-N upper trapezoidal matrix R (R is
          upper triangular if m >= n); the elements below the diagonal,
          with the array TAU, represent the orthogonal matrix Q as a
          product of min(m,n) elementary reflectors (see Further
          Details).

          TAU is DOUBLE PRECISION array, dimension (min(M,N))
          The scalar factors of the elementary reflectors (see Further
          Details).

```


Q is expressed in terms of the above outputs


```
  The matrix Q is represented as a product of elementary reflectors

     Q = H(1) H(2) . . . H(k), where k = min(m,n).

  Each H(i) has the form

     H(i) = I - tau * v * v**T

  where tau is a real scalar, and v is a real vector with
  v(1:i-1) = 0 and v(i) = 1; v(i+1:m) is stored on exit in A(i+1:m,i),
  and tau in TAU(i).

```


There is a LAPACK subroutine that [generates](http://www.netlib.org/lapack/explore-html/d9/d1d/dorgqr_8f.html) the Q matrix, so I was wondering if it'd be desirable to expose that function as well?

A stackoverflow [answer](http://stackoverflow.com/questions/21970510/solving-a-linear-system-with-lapacks-dgeqrf) said (Remark at end of top answer) that for solving purposes Q is not needed as it can be passed as input at the same format.

**Comment by wlevine** [comment]
Good to hear what you've got so far. Eventually, I think you would want to
expose all the functions related to the QR factorization, and also make
Ruby functions with nice interfaces both for solving, and for returning Q
and R directly. See what we already have for the other
factorization/decomposition methods.

**Comment by agisga** [comment]
Nice job! I agree with @wlevine. For example in NMatrix we have methods such as `#potrf` and `#getrf` which behave exactly like their lapack versions, but the corresponding methods `#factorize_cholesky` and `#factorize_lu` give a more intuitive and user friendly output (see [here](https://github.com/SciRuby/nmatrix/blob/305e7a5647108f0eb1063150cc00bcd556965bd3/lib/nmatrix/math.rb#L204)). Analogously, we could have a lapack-like `#dgeqrf` and a user-friendly `#factorize_qr` (though this can also be a separate issue/pull request).

**Comment by gau27** [comment]
Thanks for the advice @wlevine  @agisga  ; I'm currently working to make a full-fledged interface for QR factorization, but I have some doubts :-

In my `nm_lapacke_lapacke_geqrf` function definition in `math_lapacke.cpp`, I'm using a switch block to determine the type of the output tau array. (in/out for the LAPACKE function)

```
    switch(dtype) {
      case nm::FLOAT32:
        tau = NM_ALLOCA_N(float, K);
        break;

      case nm::FLOAT64:
        tau = NM_ALLOCA_N(double, K);
        break;

      case nm::COMPLEX64:
        tau = NM_ALLOCA_N(nm::Complex64, K);
        break;

      case nm::COMPLEX128:
        tau = NM_ALLOCA_N(nm::Complex128, K);
        break;
     }
```

This seemed to be the only way to do this since I can't define templates in `math_lapacke.cpp` , however I have two problems :-

1) How do I declare the tau array outside the switch block without knowing the data type before the switch block? `void* tau;` seems to give a bunch of errors and warnings.

2) After calling the LAPACKE C function, I need to convert the C array into a Ruby Array, this is straightforward for `double`, (And I suppose  `DBL2NUM((double *) float_tau[i])`  handles C floats) , but how do I convert nm::Complex64 into a Ruby complex value?

**Comment by wlevine** [comment]
I think what you want is for `tau` to be a 1-D NMatrix rather than an array. That way the memory is allocated beforehand and you don't need to worry about converting from C arrays to Ruby arrays. For example, see what we do in geev, where `w` contains the list of eigenvalues. I think this is an analogous situation.

**Comment by gau27** [comment]
Thank you @wlevine  , that made things a lot more simple and now I can successfully get Q from `geqrf`, however `dorgqr` won't suffice for computing Q for rectangular matrices, as the input matrix A (mxn) cannot hold the output mxm Q if m > n.

There are two ways to get Q for all matrices, mentioned in this forum post here https://icl.cs.utk.edu/lapack-forum/viewtopic.php?t=326

A call to `xORGQR/xUNGQR` would require supplying a new identity matrix of mxm dimension to be overwritten by Q on output.

Another method `xORGRQ` overwrites A itself but assumes that A has been declared with at least m columns (Which would make things messy for a user outside the interface in my opinion)

I'm able to get Q and R matrices using `xORGQR` as of now, I have yet to expose `xUNGQR` to get Q out of complex QR factorizations.
