### ISSUE TITLE
Create hilbert and inverse hilbert matrices of given dimension

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#441]
A function like `NMatrix.hilbert(dim)` and `NMatrix.inverse_hilbert(dim)` would be great for creating [Hilbert matrices](http://in.mathworks.com/help/matlab/ref/hilb.html).

**Comment by GauravTamba** [comment]
Could I give this a shot? I should have something in a few days.

**Comment by mohawkjohn** [comment]
What are Hilbert matrices useful for?

**Comment by v0dro** [comment]
Well, for example I came across a use case where a Hilbert matrix and an inverse hilbert matrix had been generated and then a function for computing the inverse of a matrix was used on the hilbert matrix, the result of which was compared with the inverse hilbert matrix that had been already generated.

Plus it's present in all of software suites I've come across. Might be useful for someone here too.
