### ISSUE TITLE
Remove ruby-head from necessary checks on Travis

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#445]
The build is [failing strangely for ruby-head for this issue](https://travis-ci.org/SciRuby/nmatrix/jobs/105704026#L616), but passing fine all other ruby versions (including 2.3).

IMO ruby-head should be moved to allowed failures.

**Comment by v0dro** [comment]
@mrkn can you have a look?

**Comment by mrkn** [comment]
It makes sense to move ruby-head to allow failures.

And I'll investigate the failure on ruby-head.
Thanks for notifying to me.

**Comment by mohawkjohn** [comment]
Why remove it? It sounds like we should fix the problem.

**Comment by v0dro** [comment]
Well, the failure does not happen when I use ruby-head on my PC. Plus, supporting nmatrix on the bleeding edge ruby version does not seem worth the effort.

I think the bug being caused now might be in Ruby, and will mostly be fixed soon.

**Comment by mohawkjohn** [comment]
Yeah, sure, let's go ahead and remove it.
