### ISSUE TITLE
Make all code conform to 80 characters per line

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#446]
Ok maybe we can leave the template tables code out of this, but the rest of the codebase which people work on frequently should strictly be upto 80 chars per line. It's very annoying when code starts flying off the screen. Line wrap does not help.

**Comment by Arafatk** [comment]
@v0dro I installed rubocop. And then used `rubocop --only LineLength`. 
I got 1710 offences where line length was greater than it should be.   I tried using auto correct but that does not fix the line length exceeded error and also makes a lot of other changes that we might not

**Comment by v0dro** [comment]
This should only be restricted to files which people use and work with. So you should not change the template table files.

I'd suggest doing it manually as and when you get time, such that the code looks good even though it has been split into multiple lines.

**Comment by Arafatk** [comment]
@v0dro I am sorry but i am unable to completely understand you. I have a few questions.

1. Can you elaborate on what template tables are? 
2. Should i also apply the 80 character limit to docs? 
3. Is it okay,if i send a pr correcting the line lengths  of some 5 files in `nmatrix/lib` directory and then  you could review it,After that,I will make changes for all files ?

**Comment by mohawkjohn** [comment]
In addition, someone should update all of the copyright messages.

But I want to be clear that doing this does not count as a code contribution for GSoC applicants. =)

**Comment by Arafatk** [comment]
@mohawkjohn I will do it.Can you elaborate on  what should be the updates to copyright message? 
Thanks

**Comment by mohawkjohn** [comment]
The copyright years need to be updated.

**Comment by v0dro** [comment]
And yes you can change some files in `lib/`.
