### ISSUE TITLE
about the argument and the result of NMatrix#reshape

### ISSUE THREAD

**Issue by allen-ng** [SciRuby/nmatrix#448]
_If the content seems offensive I'm sorry about that, but I'm not meant to say something that way. And that might because of my poor English_
I created a matrix like this:
```
[38] pry(main)> x
=> 
[
  [1, 2, 3]   [1, 2, 3]   [1, 2, 3]   [1, 2, 3] ]
```

Then I called reshape and found it went like this:
```
[39] pry(main)> x.reshape(2,2,3)
=> 
{ layers:
  [
    [1, 1]
    [1, 1]
  ]

  [
    [2, 2]
    [2, 2]
  ]

  [
    [3, 3]
    [3, 3]
  ]
}
```
It seems like this is a column major reshape and the first dimension is placed last.
Well, then I tried this:
```
[40] pry(main)> x.reshape(3,2,2)
=> 
{ layers:
  [
    [1, 3]
    [2, 1]
    [3, 2]
  ]

  [
    [2, 1]
    [3, 2]
    [1, 3]
  ]
}
```
and I expected the first or the third dimension to be 3 but actually the second dimension is now 3, which is a bit confusing for me.
So I wonder why is reshape designed to action like this?

---

By the way, in numpy, the result of a similar operation is listed as follows:
```
In [19]: x
Out[19]: 
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]: x.reshape(2,2,3)
Out[20]: 
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [21]: x.reshape(3,2,2)
Out[21]: 
array([[[1, 2],
        [3, 1]],

       [[2, 3],
        [1, 2]],

       [[3, 1],
        [2, 3]]])

```
And I feel more comfortable with this result.

**Comment by mohawkjohn** [comment]
I'm not 100% certain I understand your question. Could it be that NMatrix just displays it differently from NumPy? If you reshape using 3,2,2 and then call shape, it returns [3,2,2], as it should.

**Comment by allen-ng** [comment]
Oops, sorry, I'm confused by the output, thanks!
