### ISSUE TITLE
NMatrix#reshape! doesn't operate properly on specific input.

### ISSUE THREAD

**Issue by allen-ng** [SciRuby/nmatrix#449]
Hello, I tried something like this in `rake pry`:
```
[2] pry(main)> x =N[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]] #.reshape!(2,3,2,1,1)
=> 
{ layers:
  [
    [1, 1]
    [1, 1]
  ]

  [
    [2, 2]
    [2, 2]
  ]

  [
    [3, 3]
    [3, 3]
  ]
}
[3] pry(main)> x.reshape(2,3,2,1,1)
=> [[[[[1]], [[2]]], [[[3]], [[1]]], [[[2]], [[3]]]], [[[[1]], [[2]]], [[[3]], [[1]]], [[[2]], [[3]]]]]
```
And it works fine I think, but if I use `x.reshape!(2,3,2,1,1)` instead, pry will simply crash.

I wonder is this a bug or is it just designed to be like this?
If this is a bug, I'm willing to fix it.

---

By the way, I'm not sure if the shortcut N works fine in the case above, because I expect `N[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]] ` to be 
```
[
  [ [1, 2, 3],
    [1, 2, 3] ],
  [ [1, 2, 3],
    [1, 2, 3] ],
]
```
And I mentioned this in issue #448

**Comment by allen-ng** [comment]
It seems that this only occurs in pry.
It is fine outside pry.

**Comment by mohawkjohn** [comment]
Actually, I think it's not fine! I got a segfault in Pry, which means if you're not seeing it in IRB, it's probably a memory-related problem. Thanks for reporting this.
