### ISSUE TITLE
NMatrix.linspace() function

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#453]
A `linspace` function similar to [this one](http://octave.sourceforge.net/octave/function/linspace.html) would be useful.

The arguments for the nmatrix version can be as follows:

``` ruby
 NMatrix.linspace( base, limit, [shape1, shape2, ...])
```

The function will compute number of elements based on shape Array. In case shape is not specified, assume it to be `[100]`.

**Comment by Arafatk** [comment]
@v0dro I am on it.

**Comment by Arafatk** [comment]
@v0dro I am on it just a few questions? 
Are base and limit always scalars? 
Just for understanding purpose,What should be the output for  ?
` NMatrix.linspace( 2, 10, [1, 2, 3])`

**Comment by mohawkjohn** [comment]
I totally agree! This would be a great feature, @v0dro.

@Arafatk Have you looked at the Matlab linspace method? I think ours should behave similarly.
