### ISSUE TITLE
Add a new pseudo inverse function

### ISSUE THREAD

**Issue by allen-ng** [SciRuby/nmatrix#463]
It is like the `pinv` in Matlab,
This is useful when solving some equations and then the solution is something like:
`(X'X)^(-1)X'y` and `X'X` is invertible.

This may be the solution to some linear regressions (which I encountered in the machine learning course).

**Comment by mohawkjohn** [comment]
I think this is an excellent idea.

**Comment by aelnouby** [comment]
@mohawkjohn i want to work on this idea , i am just getting started , so i am not sure where this should be implemented exactly ?

**Comment by aelnouby** [comment]
Another question , when trying to get the SVD using `gesvd` just as in the documentation it always outputs "gesvd requires either the nmatrix-atlas or nmatrix-lapacke gem" , i believe atlas and lapacke are installed correctly

What is the best way available to get the SVD ?

**Comment by wlevine** [comment]
You need to 'require nmatrix/lapacke', but someone has already submitted a pull request for implementing pseudo inverse using gesvd: #471

**Comment by aelnouby** [comment]
@wlevine  i see , sorry i should have checked the PRs first. Any recommendations for a good issue to start with ?

**Comment by v0dro** [comment]
#410 is pretty simple.
