### ISSUE TITLE
Add a NMatrix#magic function

### ISSUE THREAD

**Issue by shahsaurabh0605** [SciRuby/nmatrix#466]
A function like [magic()](http://in.mathworks.com/help/matlab/ref/magic.html) is used in probability theory and has other several applications.
I have my ideas to implement the function. I thought it might be good if we discuss it.

**Comment by mohawkjohn** [comment]
I think this would be a great addition.

**Comment by shahsaurabh0605** [comment]
I am working on it and submit a PR as soon as possible

**Comment by v0dro** [comment]
Shouldn't the private functions be in a separate module called `MagicHelpers`?
