### ISSUE TITLE
C API function to change type

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#478]
Something lacking in the nmatrix C API is the ability to change the data type of the NMatrix in native code. Having a function like `rb_nmatrix_change_type(VALUE nmatrix, dtype_t new_dtype)` would be great.

**Comment by wlevine** [comment]
What do you think is lacking in the current cast functions?

**Comment by mohawkjohn** [comment]
Yeah, this is what `nm_cast` and `nm_cast_with_ctype_args` are for.

**Comment by v0dro** [comment]
Sorry my bad. Missed them..
