### ISSUE TITLE
#last for NMatrix

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#481]
Access the last element.

**Comment by mohawkjohn** [comment]
Okay, this is a very good example of why we shouldn't label issues as enhancement until they've been reviewed by others.

Before an issue can be attempted, we need to come to an understanding of what the feature would actually look like.

In this case, does `last` give just the very last element? Or does it give the last column? Or the last row?

Finally, isn't `last` part of `Enumerable`?

**Comment by v0dro** [comment]
Agreed. Will do.

About last, it should function just like `Array#last` and return the last element. And no, it's not a part of Enumerable - http://ruby-doc.org/core-2.1.0/Enumerable.html

**Comment by gau27** [comment]
My current method for this has too much overhead (apologies for overlooking that), but I can't think of a way for doing this for a general size matrix without traversing or flattening the matrix. 

I can't think of an efficient way yet for doing it in Ruby, perhaps writing in C would do the trick but I'm not sure if that's warranted here. I'll continue searching though.

**Comment by mohawkjohn** [comment]
@v0dro Why would someone need the last element of a 2D matrix? What makes the last element any more important than the lower left-hand corner element?

I do see it as being useful for vectors. We've got a few vector-only methods.

**Comment by v0dro** [comment]
It's quite useful when writing tests where you create a large matrix after doing some computations and verify only the first, last and few in-the-middle elements for reducing the number of values you need to cross check. That's how I felt the need for it anyway. It'll also help maintain some consistency with `Array`.

**Comment by mohawkjohn** [comment]
Okay. What about `x[-1,-1]`?

How do you envision this being implemented efficiently across all of the different stypes?

**Comment by v0dro** [comment]
Unless it's not TOO slow I don't think it we should spend too much time thinking about it being very fast. The reason being that it's just returning one element that the user can save in a variable for later use. Also, since NMatrix is designed such that values can't be added or removed (like `Array#<<`) in the same object, the last element will remain constant for each object thus further facilitating storing the last element in a user created variable.

Moreover, this is more of a convenience function. If it turns out to be too slow for a given use case, users can always refer to the exact element as per the shape of the matrix.

Here's how it can be implemented:
```ruby
n = NMatrix.new(
# whatever inside
) 
n[*n.shape.map { |s| s - 1} ]
# produce last element for any stype.
```

**Comment by mohawkjohn** [comment]
You didn't answer my question. =)

Also, I'm not clear on what you're saying about the last element remaining constant.

**Comment by v0dro** [comment]
So say you want the last element of an NMatrix. For a given NMatrix object, since NMatrix does not allow adding/removing elements, the last element of a given object will ALWAYS be the same, so you don't need to call `#last` on that object repeatedly to access the last element, you can just save it after calling `#last` once.

And yes `x[-1,-1-]` seems fine for implementing `last`. @gau27 has done the same thing.

**Comment by mohawkjohn** [comment]
Ahh, good call. I misread the code. Thanks for pointing that out.
