### ISSUE TITLE
Expose lapack/atlas SCAL as #scale! and #scale

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#484]
Having a destructive `#scale!` would be a great addition to multiply each element in an NMatrix with a given number.

Also the non-destructive version.

**Comment by mohawkjohn** [comment]
That's what `*=` is, isn't it?

**Comment by v0dro** [comment]
`*=` will duplicate the object and then apply changes. It's not in-place, which might prove faster in some cases.

**Comment by mohawkjohn** [comment]
Ahh, so you were thinking of a functionality analogous to `SCAL` in atlas? There's actually a function for this which should already be implemented in C. It just needs to be exposed if it hasn't already been.

**Comment by v0dro** [comment]
Hmm sure! A more human friendly wrapper to the ATLAS function would be helpful though. Also a hand made version in case there is no ATLAS.

**Comment by lds56** [comment]
Hi! I'm trying this but got a little confused. In my opinion, the `#scale` and `#scale!` may change the dtype of the matrix (e.g. `N[1, 2].scale(0.2)`). It's ok for the non-destructive `#scale` since `#cast` can be used to clone a new matrix while it's not for `#scale!`. So I want to know whether there is an in-place cast method.

**Comment by mohawkjohn** [comment]
I think if you called `#scale!` in a way that would change the dtype, it should probably give an error. There is no in-place cast method.

**Comment by lds56** [comment]
@mohawkjohn OK. And here's the pull request :) Please take a look to see if I understood it correctly.

**Comment by mohawkjohn** [comment]
Perhaps we should also override `*=` to use `scal!`. Is this feasible?

**Comment by v0dro** [comment]
Wont that be unanticipated behaviour?

You tend to expect a new object with `*=`. It's true ruby-wide.

**Comment by mohawkjohn** [comment]
Yes, good point.
