### ISSUE TITLE
Documentation for LAPACK-derived functions not showing up on rdoc

### ISSUE THREAD

**Issue by wlevine** [SciRuby/nmatrix#489]
There's no documentation for the functions on this page: http://sciruby.com/nmatrix/docs/NMatrix/LAPACK.html

However most of these functions have documentation in the source, see e.g. https://github.com/SciRuby/nmatrix/blob/ea3a544fc72dd614bb964053b89be476e45e5428/lib/nmatrix/lapack_core.rb#L119

The problem is that all of these functions have multiple implementations; one that's just a dummy implementation that throws an exception if nmatrix-lapacke isn't installed and another implementation that is loaded by nmatrix-lapacke to do the real work. The documentation is currently included only with the dummy implementation and rdoc, for whatever reason, is picking up the other implementation without documentation.

**Comment by mohawkjohn** [comment]
Are you sure it's not just because we haven't updated the docs on the Octopress lately, @wlevine?

**Comment by wlevine** [comment]
They're still missing when I run rdoc locally.

**Comment by aki94** [comment]
hey can i work on this i am a beginner  and looking to apply for gsoc please help

**Comment by mohawkjohn** [comment]
Deprecated by the switch to the plugin architecture, I believe.
