### ISSUE TITLE
nrm2 tests fail in Windows

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#495]
See #494.

**Comment by preetpalS** [comment]
After running bundle install (assuming you had already installed the nmatrix gem yourself), the rspec test suite does not run.

`am@LAPTOP-HKNNRJMM MINGW64 ~/nmatrix
$ bundle install
Resolving dependencies...
Using rake 10.5.0
Using backports 3.6.8
Using bundler 1.11.2
Using coderay 1.1.1
Using diff-lcs 1.2.5
Using json 1.8.3
Using method_source 0.8.2
Using slop 3.6.0
Using rspec-core 2.99.2
Using rspec-mocks 2.99.4
Using rake-compiler 0.9.7
Using packable 1.3.8
Using rspec-expectations 2.99.2
Using rdoc 4.2.2
Using pry 0.10.3
Using rspec-longrun 1.0.1
Using nmatrix 0.2.1 from source at `.`
Using rspec 2.99.0
Using nmatrix-atlas 0.2.1 from source at `.`
Using nmatrix-fftw 0.2.1 from source at `.`
Using nmatrix-lapacke 0.2.1 from source at `.`
Bundle complete! 11 Gemfile dependencies, 21 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

am@LAPTOP-HKNNRJMM MINGW64 ~/nmatrix
$ rake spec
C:/msys64/home/am/nmatrix/lib/nmatrix/nmatrix.rb:38:in `require': cannot load such file -- nmatrix.so (LoadError)
        from C:/msys64/home/am/nmatrix/lib/nmatrix/nmatrix.rb:38:in `<top (required)>'
        from C:/msys64/home/am/nmatrix/lib/nmatrix.rb:28:in `require'
        from C:/msys64/home/am/nmatrix/lib/nmatrix.rb:28:in `<top (required)>'
        from C:/msys64/home/am/nmatrix/spec/spec_helper.rb:30:in `require'
        from C:/msys64/home/am/nmatrix/spec/spec_helper.rb:30:in `<top (required)>'
        from C:/msys64/home/am/nmatrix/spec/00_nmatrix_spec.rb:28:in `require'
        from C:/msys64/home/am/nmatrix/spec/00_nmatrix_spec.rb:28:in `<top (required)>'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
        from C:/msys64/mingw64/lib/ruby/gems/2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
C:/msys64/mingw64/bin/ruby.exe -S rspec spec/00_nmatrix_spec.rb spec/01_enum_spec.rb spec/02_slice_spec.rb spec/03_nmatrix_monkeys_spec.rb spec/blas_spec.rb spec/elementwise_spec.rb spec/homogeneous_spec.rb spec/io/fortran_format_spec.rb spec/io/harwell_boeing_spec.rb spec/io_spec.rb spec/lapack_core_spec.rb spec/math_spec.rb spec/nmatrix_yale_spec.rb spec/rspec_spec.rb spec/shortcuts_spec.rb spec/slice_set_spec.rb spec/stat_spec.rb failed
C:/msys64/mingw64/bin/ruby.exe -S rspec spec/00_nmatrix_spec.rb spec/01_enum_spec.rb spec/02_slice_spec.rb spec/03_nmatrix_monkeys_spec.rb spec/blas_spec.rb spec/elementwise_spec.rb spec/homogeneous_spec.rb spec/io/fortran_format_spec.rb spec/io/harwell_boeing_spec.rb spec/io_spec.rb spec/lapack_core_spec.rb spec/math_spec.rb spec/nmatrix_yale_spec.rb spec/rspec_spec.rb spec/shortcuts_spec.rb spec/slice_set_spec.rb spec/stat_spec.rb`

**Comment by preetpalS** [comment]
The test suite actually still passes on Windows, I made a mistake during the testing process of not rebuilding the library itself as I assumed it was using the installed gem (so the test suite was running against an older version of the nmatrix.so file (see the `if` statement beginning on line 33 of lib/nmatrix/nmatrix.rb) as I did not rerun the `bundle exec rake compile` step before running `bundle exec rake spec`):

`Finished in 0.81021 seconds
1410 examples, 0 failures, 82 pending
C:/msys64/mingw64/bin/ruby.exe -S rspec spec/00_nmatrix_spec.rb spec/01_enum_spec.rb spec/02_slice_spec.rb spec/03_nmatrix_monkeys_spec.rb spec/blas_spec.rb spec/elementwise_spec.rb spec/homogeneous_spec.rb spec/io/fortran_format_spec.rb spec/io/harwell_boeing_spec.rb spec/io_spec.rb spec/lapack_core_spec.rb spec/math_spec.rb spec/nmatrix_yale_spec.rb spec/rspec_spec.rb spec/shortcuts_spec.rb spec/slice_set_spec.rb spec/stat_spec.rb`

`$ git rev-parse HEAD

92da6e583808a9d8a0dd9fb1a63cfd9489273f02`

**Comment by mohawkjohn** [comment]
Ah! Got it. Thanks so much for pursuing this one.
