### ISSUE TITLE
Gem installation fails on Windows since extconf.rb cannot detect g++ version

### ISSUE THREAD

**Issue by preetpalS** [SciRuby/nmatrix#498]
When installing nmatrix from the master branch of this repository from the Command Prompt or Powershell using the Ruby from http://rubyinstaller.org, the installation fails because the method `gplusplus_version` on line 128 of `ext/nmatrix/extconf.rb` tries to use the null device on Windows using `/dev/null` when it should really be trying to use the null device using `nul`.

**Comment by preetpalS** [comment]
When I got the gem to compile on Windows, I bypassed this by making the method 'gplusplus_version' just return the version string. Maybe there should be a way to manually give the g++ version (apologies if a way already exists). This is one of two blockers that I found for installing the gem using the Ruby (2.3.0 x64) from http://rubyinstaller.org/ (the other blocker is that you need to have the devkit always on your path to be able to use the gem which I think is caused because the gem doesn't statically link with some library).

**Comment by mohawkjohn** [comment]
Fixed by #502.
