### ISSUE TITLE
Unsigned data types

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#520]
Having unsigned data types of all the currently supported data types would be great. Though something tells me we'd need a rework of the way nmatrix handle data types.

**Comment by mohawkjohn** [comment]
Can you provide a use-case? No one could the last time we considered this.
Also, adding dtypes multiplies compile time.

**Comment by v0dro** [comment]
Timestamps, characters, signal data taken from DSP software, A2D and D2A conversion, image data, large value storage in general etc.

**Comment by mohawkjohn** [comment]
Why not just store these as signed? Or, for that matter, `:object`, since Ruby provides big number support?

**Comment by v0dro** [comment]
One of the primary reasons why we use nmatrix in daru is for storage. By limiting the array size and the deciding the data type, NMatrix can leverage bare to metal performance which Ruby can't. Storing anything as `:object` is as good as storing it as Array. You very well know that every single element will be added to that linked list in the nmatrix code so that it can be garbage collected later. This is a big overhead in terms of space and is a burden on the GC too.

Above all, computations using `BigDecimal` are slow,  and cannot take advantage of high speed libraries that NMatrix interfaces with.

And what if the numbers get too big? We need to upgrade from 32 bit int to 64 bit int just for the simple reason that NMatrix does not support 32 bit unsigned int.

**Comment by v0dro** [comment]
Why are you so against revamping data types? I remember being horrified by the template tables the first time I tried dabbling with nmatrix.

**Comment by v0dro** [comment]
And anyway I think the data types infra needs a serious overhaul. I remember being horrified by the template tables the first time I saw the code base.

**Comment by mohawkjohn** [comment]
Yes. The template tables are bad, but there aren't a lot of better ways to accomplish this. If you can think of one, I'd love to hear it.

Any way you come up with is going to dramatically increase compile time. You need to have a compelling reason to do that.

**Comment by mohawkjohn** [comment]
I'm going to close this until there's a design proposal associated with it.

**Comment by v0dro** [comment]
Why not keep it open so that someone with interest can read it and come up with something? Also, why is compile time such a big deal? It happens just once during gem installation. There are so many projects with large compile time that are doing just fine.

**Comment by mohawkjohn** [comment]
Find me another NMatrix dev who agrees with you and I'll reopen it. =)

**Comment by v0dro** [comment]
@wlevine and @agarie? Thoughts?

**Comment by wlevine** [comment]
One thing to keep in mind with unsigned types, is that algorithms that seem to be generic can fail with unsigned types. We already ran into this issue with the determinant (see #370), since the determinant can be negative even if all the values are positive.

Strictly speaking, from a linear algebra point of view, even signed integer matrices are illegitimate, since a vector space needs to be defined over a field (real numbers, complex numbers, or rationals). So I think this just comes down to whether you think of nmatrix as just a linear algebra library, or also a generic way to store matrix-shaped data. Obviously the latter is useful for daru, but it may be outside the scope of nmatrix. I think that's John's call.

**Comment by v0dro** [comment]
For me it's also a generic way to sore matrix-shaped data. The fact that we've moved to a plugin architecture that makes nmatrix not depend on linear algebra libraries by default is reason enough to show that it can and should be used for storing matrix-shaped data.
