### ISSUE TITLE
Unable to detect g++ version on Windows

### ISSUE THREAD

**Issue by gau27** [SciRuby/nmatrix#528]
I was trying to install NMatrix on a friend's laptop but got the following error :-

Using Windows 8.1 with a fresh install of Ruby 2.3 and Cygwin

```
C:\Users\[EditedOut]\Documents\GitHub\spice_rub [master ≡]> gem install nmatrix
Building native extensions.  This could take a while...
ERROR:  Error installing nmatrix:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.1/ext/nmatrix
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160715-11888-twlmvz.rb extconf.rb
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Exception `RuntimeError' at extconf.rb:128 - unable to determine g++ version (match to get version was nil)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
```

I'm guessing the main error is this `Exception RuntimeError' at extconf.rb:128 - unable to determine g++ version (match to get version was nil)`

Here's the output of `gcc -v`

```
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-5.4.0-1.x86_64/src/gcc-5.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc
/gcc-5.4.0-1.x86_64/src/gcc-5.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/
share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-c
ygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --
enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=
generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomi
c --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp
 --enable-libada --enable-libgcj-sublibs --disable-java-awt --disable-symvers --with-ecj-jar=/usr/share/java/ecj.jar --w
ith-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix
--with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 5.4.0 (GCC)
```

**Comment by mohawkjohn** [comment]
You can troubleshoot this by looking in `lib/nmatrix/mkmf.rb` at the `gplusplus_version`. You'll want to add `require 'pry'; binding.pry` to that function and see how it's reading `major`, `minor`, and `patch`.

**Comment by preetpalS** [comment]
@gau27 Try a later version of this library (in particular, version 0.2.3). I dealt with this [issue](https://github.com/SciRuby/nmatrix/issues/498) before on Windows and submitted a fix that was merged into the master branch (but this occurred after the particular release of the gem that you are trying to use).  I did not specifically test the fix on Cygwin, but there's a good chance it'll work since I did test the fix on MSYS2. If you can install version 0.2.3 of the library, but you still need to use version 0.2.1 of the library on Cygwin, you can try forking the library at the point of that release and cherry-picking this [commit](https://github.com/SciRuby/nmatrix/commit/b84da06c99b1d78c38d4238308bedd50e808ee79).

**Comment by preetpalS** [comment]
This issue should be closed IMO since this issue is fixed in recent releases of nmatrix.
