### ISSUE TITLE
Abstracted mkmf.rb not working correctly, can't install v0.2.2

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#532]
Caused by #530 changes to extconf.rb.

@mrkn Bad news. Trying to do a release right now, and I get the following error when installing the NMatrix gem or any of the plugins:

$ gem install nmatrix
Building native extensions.  This could take a while...
ERROR:  Error installing nmatrix:
    ERROR: Failed to build gem native extension.

    current directory: /Users/jwoods/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.2/ext/nmatrix
/Users/jwoods/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20160722-5447-q72mv3.rb extconf.rb
/Users/jwoods/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- nmatrix/mkmf (LoadError)
    from /Users/jwoods/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from extconf.rb:28:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/jwoods/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.2 for inspection.
Results logged to /Users/jwoods/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/nmatrix-0.2.2/gem_make.out
Can you troubleshoot this ASAP?

**Comment by mrkn** [comment]
@mohawkjohn I'll investigate it today.  Sorry for inconvenience.
