### ISSUE TITLE
Open a Gitter Room for NMatrix

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/nmatrix#537]
A Gitter room is very helpful for someone who wants to query on how to accomplish small tasks like "how to initialize NMatrix from columns". Its better than IRC in the case that the messages persist even after one goes offline and one can find the reply later on.

**Comment by v0dro** [comment]
+1 to that!

**Comment by mohawkjohn** [comment]
https://gitter.im/SciRuby/nmatrix
