### ISSUE TITLE
NMatrix getter and setter way slower than Matrix

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/nmatrix#541]
I'm using NMatrix for [competitive programming](https://en.wikipedia.org/wiki/Competitive_programming) for a while now and I have found NMatrix to be **slower** than Matrix for most of my programs. For example methods such as `[]`, `[]=` which are frequently used in my programs are slower in NMatrix.

[Here](https://gist.github.com/lokeshh/cc7b428fda100dedb005067c01b355db)'s a benchmark I ran and following are the results:

```ruby
       user     system      total        real
Matrix getter  3.700000   0.020000   3.720000 (  3.744560)
NMatrix getter 12.930000   0.060000  12.990000 ( 13.065677)
Matrix setter  2.920000   0.020000   2.940000 (  2.965361)
NMatrix setter 16.600000   0.060000  16.660000 ( 16.889194)
```

**Comment by v0dro** [comment]
Damn that sucks. Need some urgent performance fixes for nmatrix.

**Comment by wlevine** [comment]
@lokeshh Good catch! I think this is due to a lot of [heap allocation of SLICE objects](https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/ruby_nmatrix.c#L2638), which can be avoided. I will try to have a patch soon.

**Comment by wlevine** [comment]
For `#[]=`, I notice that we're spending a lot of time in [`nm::dense_storage::set()`](https://github.com/SciRuby/nmatrix/blob/7f3fa5d2e1e858b5c7df7136fd899da7f590c018/ext/nmatrix/storage/dense/dense.cpp#L125), allocating and freeing stuff. I'm not going to look into this any more at the moment, just noting this for future reference.

**Comment by mohawkjohn** [comment]
Thanks for looking into this, @wlevine. I concur with your explanation.
