### ISSUE TITLE
Feature: Create NMatrix from binary files and binary strings

### ISSUE THREAD

**Issue by prasunanand** [SciRuby/nmatrix#547]
I am interested in parsing a binary file. Numpy supports reading binary file. [Link](https://github.com/numpy/numpy/blob/c90d7c94fd2077d0beca48fa89a423da2b0bb663/numpy/core/records.py#L721) . I will try to implement it.

**Comment by mohawkjohn** [comment]
This feature already exists: https://github.com/SciRuby/nmatrix/blob/7f3fa5d2e1e858b5c7df7136fd899da7f590c018/ext/nmatrix/ruby_nmatrix.c#L1704

See #104 for areas needing improvement.
