### ISSUE TITLE
Finish pending work in pull requests

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#562]
Adding this task for GSOC students looking for something to do.

There are a lot of open pull requests that just need a few changes, but people have gotten behind or forgotten to finish. You can go revise some of these to get them merged; just open an issue to make it clear you're working on the PR.

**Comment by aki94** [comment]
is anyone working on it. can i work on this?

**Comment by mohawkjohn** [comment]
Pick a specific pull request, @aki94, and ask on that one. :)
