### ISSUE TITLE
'bundle exec rake compile' command gives error

### ISSUE THREAD

**Issue by npochhi** [SciRuby/nmatrix#568]
While compiling the source code using `bundle exec rake compile`, following error appears. I'm using Ubuntu 16.04.
'bundler: failed to load command: rake (/usr/local/bin/rake)
LoadError: cannot load such file -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake
  /usr/local/bin/rake:22:in `load'
  /usr/local/bin/rake:22:in `<top (required)>'

I compiled the code by downgrading the rake version to 10.5.0 and then compiling.

**Comment by mohawkjohn** [comment]
I need more information about the nature of your Ruby installation. What version are you using? What do you mean by "downgrading the rake version?" If you do a `bundle install`, that should install the appropriate version of rake for you, without getting rid of the old one.

**Comment by npochhi** [comment]
The rake version in my system was '12.0.0', I had to downgrade it to '10.5.0'. The 'bundle install' didn't work in my case. The above-mentioned error was occurring. Actually, I'm a newbie and if others aren't getting the same error, I may have misunderstood some of the building instructions.

**Comment by mohawkjohn** [comment]
@npochhi Sorry for the delay. I'm not really sure why that would be happening. The gemspec requires rake to be version 10.3, so it shouldn't even really let you do it with 10.5.

Can you give me steps to reproduce?
