### ISSUE TITLE
nmatrix gem Fails to Install/Build

### ISSUE THREAD

**Issue by martinvahi** [SciRuby/nmatrix#597]
As the following excerpt shows, iruby installation is successful, id est 
generally the system is set up properly.

    ts2@linux-0fiz:~/tmp$ gem install iruby
    Fetching: data_uri-0.1.0.gem (100%)
    Successfully installed data_uri-0.1.0
    Fetching: mimemagic-0.3.2.gem (100%)
    Successfully installed mimemagic-0.3.2
    Fetching: bond-0.5.1.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed bond-0.5.1
    Fetching: iruby-0.3.gem (100%)
    Consider installing the optional dependencies to get additional functionality:
      * pry
      * pry-doc
      * awesome_print
      * gnuplot
      * rubyvis
      * nyaplot
    
    Successfully installed iruby-0.3
    Parsing documentation for data_uri-0.1.0
    Installing ri documentation for data_uri-0.1.0
    Parsing documentation for mimemagic-0.3.2
    Installing ri documentation for mimemagic-0.3.2
    Parsing documentation for bond-0.5.1
    Installing ri documentation for bond-0.5.1
    Parsing documentation for iruby-0.3
    Installing ri documentation for iruby-0.3
    Done installing documentation for data_uri, mimemagic, bond, iruby after 4 seconds
    4 gems installed
    ts2@linux-0fiz:~/tmp$ gem install nmatrix
    Fetching: backports-3.8.0.gem (100%)
    Successfully installed backports-3.8.0
    Fetching: packable-1.3.8.gem (100%)
    Successfully installed packable-1.3.8
    Fetching: nmatrix-0.2.3.gem (100%)
    Building native extensions.  This could take a while...
    ERROR:  Error installing nmatrix:
    	ERROR: Failed to build gem native extension.
    
        /opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ruby/paigaldatult/v_2_2_3_clang/bin/ruby -r ./siteconf20170709-27909-1b7o733.rb extconf.rb
    checking for rb_array_const_ptr() in ruby.h... no
    checking for FIX_CONST_VALUE_PTR in ruby.h... no
    checking for RARRAY_CONST_PTR in ruby.h... yes
    checking for RARRAY_AREF in ruby.h... yes
    creating nmatrix_config.h
    creating Makefile
    
    make "DESTDIR=" clean
    
    make "DESTDIR="
    compiling nmatrix.cpp
    In file included from nmatrix.cpp:44:
    In file included from ./data/data.h:47:
    ./data/ruby_object.h:113:10: error: conversion function cannot be redeclared
      inline operator uint64_t() const { RETURN_OBJ2NUM(NUM2ULONG)      }
             ^
    ./data/ruby_object.h:110:10: note: previous declaration is here
      inline operator VALUE() const { return rval; }
             ^
    1 error generated.
    Makefile:244: recipe for target 'nmatrix.o' failed
    make: *** [nmatrix.o] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/gem_home/gems/nmatrix-0.2.3 for inspection.
    Results logged to /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/gem_home/extensions/x86_64-linux/2.2.0/nmatrix-0.2.3/gem_make.out
    ts2@linux-0fiz:~/tmp$ uname -a
    Linux linux-0fiz 3.16.7-53-desktop #1 SMP PREEMPT Fri Dec 2 13:19:28 UTC 2016 (7b4a1f9) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:~/tmp$ date
    Sun Jul  9 11:06:45 EEST 2017
    ts2@linux-0fiz:~/tmp$ ruby -v
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    ts2@linux-0fiz:~/tmp$

**Comment by mohawkjohn** [comment]
What happens if you attempt to install the current version from git?

**Comment by mohawkjohn** [comment]
Closing due to no reply.
