### ISSUE TITLE
Check equality with tolerance

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#613]
If you're approximating a matrix and check element-wise accuracy with the original matrix, you frequently need to use equality with some tolerance. Having a function like `be_within` similar to rspec would be helpful.

For example:
``` ruby
n = NMatrix.random(8)
u,s,d = n.gesvd
assert n.be_within(0.0001, u.dot(s.dot(d)))
```

**Comment by mohawkjohn** [comment]
`(n - u.dot(s.dot(d))) <= 0.001`
