### ISSUE TITLE
Is there a 'argmax' method for NMatrix?

### ISSUE THREAD

**Issue by weili-git** [SciRuby/nmatrix#629]
By searching 'https://rdoc.info/github/SciRuby/nmatrix/NMatrix', I could only find 'max' method which returns the max value of certain dimension, but I need to get the index instead. 
Thank you so much if someone could help!

**Comment by kojix2** [comment]
Use numo-narray...
http://ruby-numo.github.io/numo-narray/yard/Numo/DFloat.html#argmax-instance_method
http://ruby-numo.github.io/numo-narray/yard/Numo/DFloat.html#max_index-instance_method
