### ISSUE TITLE
Linking problem on Mac OS X

### ISSUE THREAD

**Issue by mohawkjohn** [SciRuby/nmatrix#69]
When I try to build HEAD on Mac OS X (using `rake repackage` and then `gem install` on the `.gem` file it creates), I get the following:

```
compiling storage/list.cpp
linking shared-object nmatrix.bundle
0  0x102cb6098  __assert_rtn + 144
1  0x102cdc8af  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 1149
2  0x102cdc261  archive::File<x86_64>::justInTimeforEachAtom(char const*, ld::File::AtomHandler&) const + 139
3  0x102cecb06  ld::tool::InputFiles::searchLibraries(char const*, bool, bool, bool, ld::File::AtomHandler&) const + 210
4  0x102cf3978  ld::tool::Resolver::resolveUndefines() + 200
5  0x102cf58a3  ld::tool::Resolver::resolve() + 75
6  0x102cb6380  main + 370
7  0x102ca7cd4  start + 52
A linker snapshot was created at:
/tmp/nmatrix.bundle-2013-02-30-135555.ld-snapshot
ld: Assertion failed: (memberIndex != 0), function makeObjectFileForMember, file /SourceCache/ld64/ld64-136/src/ld/parsers/archive_file.cpp, line 354.
collect2: error: ld returned 1 exit status
make: *** [nmatrix.bundle] Error 1
```

I'm not really sure what's causing it. I imagine it's a problem with the gcc version being used to link, since I have multiple gcc and clang versions installed. But not good enough with Mac to figure out how to control those things.

This resembles an error @agarie noted on the listserv, but he didn't indicate which part of his solution actually solved that problem. He recommended reinstalling ATLAS, which isn't an option on MacBook Air, since there's no way to disable processor throttling.

**Comment by mohawkjohn** [comment]
Argh. Seeing this exact same problem again. Lovely.

**Comment by v0dro** [comment]
This still relevant?
